/* PreferencesWindow.c generated by valac 0.11.6, the Vala compiler
 * generated from PreferencesWindow.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <stdio.h>
#include <gio/gio.h>


#define BEAT_BOX_TYPE_PREFERENCES_WINDOW (beat_box_preferences_window_get_type ())
#define BEAT_BOX_PREFERENCES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_PREFERENCES_WINDOW, BeatBoxPreferencesWindow))
#define BEAT_BOX_PREFERENCES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_PREFERENCES_WINDOW, BeatBoxPreferencesWindowClass))
#define BEAT_BOX_IS_PREFERENCES_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_PREFERENCES_WINDOW))
#define BEAT_BOX_IS_PREFERENCES_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_PREFERENCES_WINDOW))
#define BEAT_BOX_PREFERENCES_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_PREFERENCES_WINDOW, BeatBoxPreferencesWindowClass))

typedef struct _BeatBoxPreferencesWindow BeatBoxPreferencesWindow;
typedef struct _BeatBoxPreferencesWindowClass BeatBoxPreferencesWindowClass;
typedef struct _BeatBoxPreferencesWindowPrivate BeatBoxPreferencesWindowPrivate;

#define BEAT_BOX_TYPE_LIBRARY_MANAGER (beat_box_library_manager_get_type ())
#define BEAT_BOX_LIBRARY_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_LIBRARY_MANAGER, BeatBoxLibraryManager))
#define BEAT_BOX_LIBRARY_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_LIBRARY_MANAGER, BeatBoxLibraryManagerClass))
#define BEAT_BOX_IS_LIBRARY_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_LIBRARY_MANAGER))
#define BEAT_BOX_IS_LIBRARY_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_LIBRARY_MANAGER))
#define BEAT_BOX_LIBRARY_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_LIBRARY_MANAGER, BeatBoxLibraryManagerClass))

typedef struct _BeatBoxLibraryManager BeatBoxLibraryManager;
typedef struct _BeatBoxLibraryManagerClass BeatBoxLibraryManagerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _BeatBoxLibraryManagerPrivate BeatBoxLibraryManagerPrivate;

#define BEAT_BOX_TYPE_SETTINGS (beat_box_settings_get_type ())
#define BEAT_BOX_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_SETTINGS, BeatBoxSettings))
#define BEAT_BOX_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_SETTINGS, BeatBoxSettingsClass))
#define BEAT_BOX_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_SETTINGS))
#define BEAT_BOX_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_SETTINGS))
#define BEAT_BOX_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_SETTINGS, BeatBoxSettingsClass))

typedef struct _BeatBoxSettings BeatBoxSettings;
typedef struct _BeatBoxSettingsClass BeatBoxSettingsClass;

#define BEAT_BOX_TYPE_DATA_BASE_MANAGER (beat_box_data_base_manager_get_type ())
#define BEAT_BOX_DATA_BASE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_DATA_BASE_MANAGER, BeatBoxDataBaseManager))
#define BEAT_BOX_DATA_BASE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_DATA_BASE_MANAGER, BeatBoxDataBaseManagerClass))
#define BEAT_BOX_IS_DATA_BASE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_DATA_BASE_MANAGER))
#define BEAT_BOX_IS_DATA_BASE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_DATA_BASE_MANAGER))
#define BEAT_BOX_DATA_BASE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_DATA_BASE_MANAGER, BeatBoxDataBaseManagerClass))

typedef struct _BeatBoxDataBaseManager BeatBoxDataBaseManager;
typedef struct _BeatBoxDataBaseManagerClass BeatBoxDataBaseManagerClass;

#define BEAT_BOX_TYPE_DATA_BASE_UPDATER (beat_box_data_base_updater_get_type ())
#define BEAT_BOX_DATA_BASE_UPDATER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_DATA_BASE_UPDATER, BeatBoxDataBaseUpdater))
#define BEAT_BOX_DATA_BASE_UPDATER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_DATA_BASE_UPDATER, BeatBoxDataBaseUpdaterClass))
#define BEAT_BOX_IS_DATA_BASE_UPDATER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_DATA_BASE_UPDATER))
#define BEAT_BOX_IS_DATA_BASE_UPDATER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_DATA_BASE_UPDATER))
#define BEAT_BOX_DATA_BASE_UPDATER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_DATA_BASE_UPDATER, BeatBoxDataBaseUpdaterClass))

typedef struct _BeatBoxDataBaseUpdater BeatBoxDataBaseUpdater;
typedef struct _BeatBoxDataBaseUpdaterClass BeatBoxDataBaseUpdaterClass;

#define BEAT_BOX_TYPE_FILE_OPERATOR (beat_box_file_operator_get_type ())
#define BEAT_BOX_FILE_OPERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_FILE_OPERATOR, BeatBoxFileOperator))
#define BEAT_BOX_FILE_OPERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_FILE_OPERATOR, BeatBoxFileOperatorClass))
#define BEAT_BOX_IS_FILE_OPERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_FILE_OPERATOR))
#define BEAT_BOX_IS_FILE_OPERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_FILE_OPERATOR))
#define BEAT_BOX_FILE_OPERATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_FILE_OPERATOR, BeatBoxFileOperatorClass))

typedef struct _BeatBoxFileOperator BeatBoxFileOperator;
typedef struct _BeatBoxFileOperatorClass BeatBoxFileOperatorClass;

#define BEAT_BOX_TYPE_STREAM_PLAYER (beat_box_stream_player_get_type ())
#define BEAT_BOX_STREAM_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_STREAM_PLAYER, BeatBoxStreamPlayer))
#define BEAT_BOX_STREAM_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_STREAM_PLAYER, BeatBoxStreamPlayerClass))
#define BEAT_BOX_IS_STREAM_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_STREAM_PLAYER))
#define BEAT_BOX_IS_STREAM_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_STREAM_PLAYER))
#define BEAT_BOX_STREAM_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_STREAM_PLAYER, BeatBoxStreamPlayerClass))

typedef struct _BeatBoxStreamPlayer BeatBoxStreamPlayer;
typedef struct _BeatBoxStreamPlayerClass BeatBoxStreamPlayerClass;

#define LAST_FM_TYPE_CORE (last_fm_core_get_type ())
#define LAST_FM_CORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAST_FM_TYPE_CORE, LastFMCore))
#define LAST_FM_CORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAST_FM_TYPE_CORE, LastFMCoreClass))
#define LAST_FM_IS_CORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAST_FM_TYPE_CORE))
#define LAST_FM_IS_CORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAST_FM_TYPE_CORE))
#define LAST_FM_CORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAST_FM_TYPE_CORE, LastFMCoreClass))

typedef struct _LastFMCore LastFMCore;
typedef struct _LastFMCoreClass LastFMCoreClass;

#define BEAT_BOX_TYPE_SONG_INFO (beat_box_song_info_get_type ())
#define BEAT_BOX_SONG_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_SONG_INFO, BeatBoxSongInfo))
#define BEAT_BOX_SONG_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_SONG_INFO, BeatBoxSongInfoClass))
#define BEAT_BOX_IS_SONG_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_SONG_INFO))
#define BEAT_BOX_IS_SONG_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_SONG_INFO))
#define BEAT_BOX_SONG_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_SONG_INFO, BeatBoxSongInfoClass))

typedef struct _BeatBoxSongInfo BeatBoxSongInfo;
typedef struct _BeatBoxSongInfoClass BeatBoxSongInfoClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _BeatBoxPreferencesWindow {
	GtkWindow parent_instance;
	BeatBoxPreferencesWindowPrivate * priv;
};

struct _BeatBoxPreferencesWindowClass {
	GtkWindowClass parent_class;
	void (*lastfmLoginClick) (BeatBoxPreferencesWindow* self);
	void (*saveClicked) (BeatBoxPreferencesWindow* self);
	void (*cancelClicked) (BeatBoxPreferencesWindow* self);
};

struct _BeatBoxPreferencesWindowPrivate {
	BeatBoxLibraryManager* _lm;
	GtkVBox* content;
	GtkHBox* padding;
	GtkLabel* musicLabel;
	GtkLabel* managementLabel;
	GtkLabel* lastfmLabel;
	GtkFileChooserButton* fileChooser;
	GtkCheckButton* organizeFolders;
	GtkCheckButton* copyImportedMusic;
	GtkButton* lastfmLogin;
	GtkLabel* lastfmInfo;
	GtkButton* saveChanges;
	gchar* lastfm_token;
};

struct _BeatBoxLibraryManager {
	GObject parent_instance;
	BeatBoxLibraryManagerPrivate * priv;
	BeatBoxSettings* settings;
	BeatBoxDataBaseManager* dbm;
	BeatBoxDataBaseUpdater* dbu;
	BeatBoxFileOperator* fo;
	BeatBoxStreamPlayer* player;
	LastFMCore* lfm;
	gint _played_index;
	gint _current_index;
	gint _current_shuffled_index;
	BeatBoxSongInfo* song_info;
	gboolean playing;
	gboolean repeat;
	gboolean shuffle;
	gboolean doing_file_operations;
};

struct _BeatBoxLibraryManagerClass {
	GObjectClass parent_class;
	void (*dbProgress) (BeatBoxLibraryManager* self, const gchar* message, gdouble progress);
};


static gpointer beat_box_preferences_window_parent_class = NULL;

GType beat_box_preferences_window_get_type (void) G_GNUC_CONST;
GType beat_box_library_manager_get_type (void) G_GNUC_CONST;
#define BEAT_BOX_PREFERENCES_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), BEAT_BOX_TYPE_PREFERENCES_WINDOW, BeatBoxPreferencesWindowPrivate))
enum  {
	BEAT_BOX_PREFERENCES_WINDOW_DUMMY_PROPERTY
};
BeatBoxPreferencesWindow* beat_box_preferences_window_new (BeatBoxLibraryManager* lm);
BeatBoxPreferencesWindow* beat_box_preferences_window_construct (GType object_type, BeatBoxLibraryManager* lm);
void beat_box_preferences_window_buildUI (BeatBoxPreferencesWindow* self);
GType beat_box_settings_get_type (void) G_GNUC_CONST;
GType beat_box_data_base_manager_get_type (void) G_GNUC_CONST;
GType beat_box_data_base_updater_get_type (void) G_GNUC_CONST;
GType beat_box_file_operator_get_type (void) G_GNUC_CONST;
GType beat_box_stream_player_get_type (void) G_GNUC_CONST;
GType last_fm_core_get_type (void) G_GNUC_CONST;
GType beat_box_song_info_get_type (void) G_GNUC_CONST;
gchar* beat_box_settings_getMusicFolder (BeatBoxSettings* self);
gboolean beat_box_settings_getUpdateFolderHierarchy (BeatBoxSettings* self);
gboolean beat_box_settings_getCopyImportedMusic (BeatBoxSettings* self);
GtkAlignment* beat_box_preferences_window_wrap_alignment (GtkWidget* widget, gint top, gint right, gint bottom, gint left);
void beat_box_preferences_window_lastfmLoginClick (BeatBoxPreferencesWindow* self);
static void _beat_box_preferences_window_lastfmLoginClick_gtk_button_clicked (GtkButton* _sender, gpointer self);
void beat_box_preferences_window_saveClicked (BeatBoxPreferencesWindow* self);
static void _beat_box_preferences_window_saveClicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void beat_box_preferences_window_real_lastfmLoginClick (BeatBoxPreferencesWindow* self);
gchar* last_fm_core_getToken (LastFMCore* self);
#define LAST_FM_CORE_api "a40ea1720028bd40c66b17d7146b3f3b"
gchar* last_fm_core_getSessionKey (LastFMCore* self, const gchar* token);
void beat_box_settings_setLastFMSessionKey (BeatBoxSettings* self, const gchar* val);
static void beat_box_preferences_window_real_saveClicked (BeatBoxPreferencesWindow* self);
void beat_box_settings_setUpdateFolderHierarchy (BeatBoxSettings* self, gboolean val);
void beat_box_settings_setCopyImportedMusic (BeatBoxSettings* self, gboolean val);
void beat_box_preferences_window_cancelClicked (BeatBoxPreferencesWindow* self);
static void beat_box_preferences_window_real_cancelClicked (BeatBoxPreferencesWindow* self);
static void beat_box_preferences_window_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


BeatBoxPreferencesWindow* beat_box_preferences_window_construct (GType object_type, BeatBoxLibraryManager* lm) {
	BeatBoxPreferencesWindow * self = NULL;
	BeatBoxLibraryManager* _tmp0_;
	BeatBoxLibraryManager* _tmp1_;
	g_return_val_if_fail (lm != NULL, NULL);
	self = (BeatBoxPreferencesWindow*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (lm);
	_tmp1_ = _tmp0_;
	_g_object_unref0 (self->priv->_lm);
	self->priv->_lm = _tmp1_;
	beat_box_preferences_window_buildUI (self);
	return self;
}


BeatBoxPreferencesWindow* beat_box_preferences_window_new (BeatBoxLibraryManager* lm) {
	return beat_box_preferences_window_construct (BEAT_BOX_TYPE_PREFERENCES_WINDOW, lm);
}


static void _beat_box_preferences_window_lastfmLoginClick_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	beat_box_preferences_window_lastfmLoginClick (self);
}


static void _beat_box_preferences_window_saveClicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	beat_box_preferences_window_saveClicked (self);
}


void beat_box_preferences_window_buildUI (BeatBoxPreferencesWindow* self) {
	GtkVBox* _tmp0_ = NULL;
	GtkVBox* _tmp1_;
	GtkHBox* _tmp2_ = NULL;
	GtkHBox* _tmp3_;
	GtkLabel* _tmp4_ = NULL;
	GtkLabel* _tmp5_;
	GtkFileChooserButton* _tmp6_ = NULL;
	GtkFileChooserButton* _tmp7_;
	GtkLabel* _tmp8_ = NULL;
	GtkLabel* _tmp9_;
	GtkCheckButton* _tmp10_ = NULL;
	GtkCheckButton* _tmp11_;
	GtkCheckButton* _tmp12_ = NULL;
	GtkCheckButton* _tmp13_;
	GtkLabel* _tmp14_ = NULL;
	GtkLabel* _tmp15_;
	GtkLabel* _tmp16_ = NULL;
	GtkLabel* _tmp17_;
	GtkButton* _tmp18_ = NULL;
	GtkButton* _tmp19_;
	GtkButton* _tmp20_ = NULL;
	GtkButton* _tmp21_;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_;
	gboolean _tmp24_;
	gboolean _tmp25_;
	GtkHButtonBox* _tmp26_ = NULL;
	GtkHButtonBox* bottomButtons;
	GtkAlignment* _tmp27_ = NULL;
	GtkAlignment* _tmp28_;
	GtkAlignment* _tmp29_ = NULL;
	GtkAlignment* _tmp30_;
	GtkAlignment* _tmp31_ = NULL;
	GtkAlignment* _tmp32_;
	GtkAlignment* _tmp33_ = NULL;
	GtkAlignment* _tmp34_;
	GtkAlignment* _tmp35_ = NULL;
	GtkAlignment* _tmp36_;
	GtkAlignment* _tmp37_ = NULL;
	GtkAlignment* _tmp38_;
	g_return_if_fail (self != NULL);
	gtk_window_set_title ((GtkWindow*) self, "Preferences");
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
	gtk_widget_set_size_request ((GtkWidget*) self, 400, 300);
	g_object_set ((GtkWindow*) self, "allow-shrink", TRUE, NULL);
	_tmp0_ = (GtkVBox*) gtk_vbox_new (FALSE, 10);
	_tmp1_ = g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->content);
	self->priv->content = _tmp1_;
	_tmp2_ = (GtkHBox*) gtk_hbox_new (FALSE, 10);
	_tmp3_ = g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->padding);
	self->priv->padding = _tmp3_;
	_tmp4_ = (GtkLabel*) gtk_label_new ("Music Folder Location");
	_tmp5_ = g_object_ref_sink (_tmp4_);
	_g_object_unref0 (self->priv->musicLabel);
	self->priv->musicLabel = _tmp5_;
	_tmp6_ = (GtkFileChooserButton*) gtk_file_chooser_button_new ("Music Folder", GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
	_tmp7_ = g_object_ref_sink (_tmp6_);
	_g_object_unref0 (self->priv->fileChooser);
	self->priv->fileChooser = _tmp7_;
	_tmp8_ = (GtkLabel*) gtk_label_new ("Library Management");
	_tmp9_ = g_object_ref_sink (_tmp8_);
	_g_object_unref0 (self->priv->managementLabel);
	self->priv->managementLabel = _tmp9_;
	_tmp10_ = (GtkCheckButton*) gtk_check_button_new_with_label ("Keep Music folder organized");
	_tmp11_ = g_object_ref_sink (_tmp10_);
	_g_object_unref0 (self->priv->organizeFolders);
	self->priv->organizeFolders = _tmp11_;
	_tmp12_ = (GtkCheckButton*) gtk_check_button_new_with_label ("Copy files to Music folder when added to Library");
	_tmp13_ = g_object_ref_sink (_tmp12_);
	_g_object_unref0 (self->priv->copyImportedMusic);
	self->priv->copyImportedMusic = _tmp13_;
	_tmp14_ = (GtkLabel*) gtk_label_new ("Last FM Integration");
	_tmp15_ = g_object_ref_sink (_tmp14_);
	_g_object_unref0 (self->priv->lastfmLabel);
	self->priv->lastfmLabel = _tmp15_;
	_tmp16_ = (GtkLabel*) gtk_label_new ("To allow for Last FM integration, you must give permission to BeatBox." \
" You only need to do this once.");
	_tmp17_ = g_object_ref_sink (_tmp16_);
	_g_object_unref0 (self->priv->lastfmInfo);
	self->priv->lastfmInfo = _tmp17_;
	_tmp18_ = (GtkButton*) gtk_button_new_with_label ("Enable Scrobbling");
	_tmp19_ = g_object_ref_sink (_tmp18_);
	_g_object_unref0 (self->priv->lastfmLogin);
	self->priv->lastfmLogin = _tmp19_;
	_tmp20_ = (GtkButton*) gtk_button_new_with_label ("Close");
	_tmp21_ = g_object_ref_sink (_tmp20_);
	_g_object_unref0 (self->priv->saveChanges);
	self->priv->saveChanges = _tmp21_;
	g_object_set ((GtkMisc*) self->priv->musicLabel, "xalign", 0.0f, NULL);
	g_object_set ((GtkMisc*) self->priv->managementLabel, "xalign", 0.0f, NULL);
	g_object_set ((GtkMisc*) self->priv->lastfmLabel, "xalign", 0.0f, NULL);
	gtk_label_set_markup (self->priv->musicLabel, "<b>Music Folder Location</b>");
	gtk_label_set_markup (self->priv->managementLabel, "<b>Library Management</b>");
	gtk_label_set_markup (self->priv->lastfmLabel, "<b>Last FM Integration</b>");
	_tmp22_ = beat_box_settings_getMusicFolder (self->priv->_lm->settings);
	_tmp23_ = _tmp22_;
	gtk_file_chooser_set_current_folder ((GtkFileChooser*) self->priv->fileChooser, _tmp23_);
	_g_free0 (_tmp23_);
	_tmp24_ = beat_box_settings_getUpdateFolderHierarchy (self->priv->_lm->settings);
	gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->organizeFolders, _tmp24_);
	_tmp25_ = beat_box_settings_getCopyImportedMusic (self->priv->_lm->settings);
	gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->copyImportedMusic, _tmp25_);
	gtk_label_set_line_wrap (self->priv->lastfmInfo, TRUE);
	_tmp26_ = (GtkHButtonBox*) gtk_hbutton_box_new ();
	bottomButtons = g_object_ref_sink (_tmp26_);
	gtk_button_box_set_layout ((GtkButtonBox*) bottomButtons, GTK_BUTTONBOX_END);
	gtk_box_pack_end ((GtkBox*) bottomButtons, (GtkWidget*) self->priv->saveChanges, FALSE, FALSE, (guint) 0);
	_tmp27_ = beat_box_preferences_window_wrap_alignment ((GtkWidget*) self->priv->musicLabel, 10, 0, 0, 0);
	_tmp28_ = _tmp27_;
	gtk_box_pack_start ((GtkBox*) self->priv->content, (GtkWidget*) _tmp28_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp28_);
	_tmp29_ = beat_box_preferences_window_wrap_alignment ((GtkWidget*) self->priv->fileChooser, 0, 0, 0, 10);
	_tmp30_ = _tmp29_;
	gtk_box_pack_start ((GtkBox*) self->priv->content, (GtkWidget*) _tmp30_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp30_);
	gtk_box_pack_start ((GtkBox*) self->priv->content, (GtkWidget*) self->priv->managementLabel, FALSE, TRUE, (guint) 0);
	_tmp31_ = beat_box_preferences_window_wrap_alignment ((GtkWidget*) self->priv->organizeFolders, 0, 0, 0, 10);
	_tmp32_ = _tmp31_;
	gtk_box_pack_start ((GtkBox*) self->priv->content, (GtkWidget*) _tmp32_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp32_);
	_tmp33_ = beat_box_preferences_window_wrap_alignment ((GtkWidget*) self->priv->copyImportedMusic, 0, 0, 0, 10);
	_tmp34_ = _tmp33_;
	gtk_box_pack_start ((GtkBox*) self->priv->content, (GtkWidget*) _tmp34_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp34_);
	gtk_box_pack_start ((GtkBox*) self->priv->content, (GtkWidget*) self->priv->lastfmLabel, FALSE, TRUE, (guint) 0);
	_tmp35_ = beat_box_preferences_window_wrap_alignment ((GtkWidget*) self->priv->lastfmInfo, 0, 0, 0, 10);
	_tmp36_ = _tmp35_;
	gtk_box_pack_start ((GtkBox*) self->priv->content, (GtkWidget*) _tmp36_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp36_);
	_tmp37_ = beat_box_preferences_window_wrap_alignment ((GtkWidget*) self->priv->lastfmLogin, 0, 0, 0, 10);
	_tmp38_ = _tmp37_;
	gtk_box_pack_start ((GtkBox*) self->priv->content, (GtkWidget*) _tmp38_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp38_);
	gtk_box_pack_end ((GtkBox*) self->priv->content, (GtkWidget*) bottomButtons, FALSE, TRUE, (guint) 10);
	gtk_box_pack_start ((GtkBox*) self->priv->padding, (GtkWidget*) self->priv->content, TRUE, TRUE, (guint) 10);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->priv->padding);
	gtk_widget_show_all ((GtkWidget*) self);
	g_signal_connect_object (self->priv->lastfmLogin, "clicked", (GCallback) _beat_box_preferences_window_lastfmLoginClick_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->saveChanges, "clicked", (GCallback) _beat_box_preferences_window_saveClicked_gtk_button_clicked, self, 0);
	_g_object_unref0 (bottomButtons);
}


GtkAlignment* beat_box_preferences_window_wrap_alignment (GtkWidget* widget, gint top, gint right, gint bottom, gint left) {
	GtkAlignment* result = NULL;
	GtkAlignment* _tmp0_ = NULL;
	GtkAlignment* alignment;
	g_return_val_if_fail (widget != NULL, NULL);
	_tmp0_ = (GtkAlignment*) gtk_alignment_new (0.0f, 0.0f, 1.0f, 1.0f);
	alignment = g_object_ref_sink (_tmp0_);
	g_object_set (alignment, "top-padding", (guint) top, NULL);
	g_object_set (alignment, "right-padding", (guint) right, NULL);
	g_object_set (alignment, "bottom-padding", (guint) bottom, NULL);
	g_object_set (alignment, "left-padding", (guint) left, NULL);
	gtk_container_add ((GtkContainer*) alignment, widget);
	result = alignment;
	return result;
}


static void beat_box_preferences_window_real_lastfmLoginClick (BeatBoxPreferencesWindow* self) {
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp1_ = gtk_button_get_label (self->priv->lastfmLogin);
	if (g_strcmp0 (_tmp1_, "Enable Scrobbling") == 0) {
		_tmp0_ = TRUE;
	} else {
		const gchar* _tmp2_ = NULL;
		_tmp2_ = gtk_button_get_label (self->priv->lastfmLogin);
		_tmp0_ = g_strcmp0 (_tmp2_, "Unsuccessful. Click to try again.") == 0;
	}
	if (_tmp0_) {
		gchar* _tmp3_ = NULL;
		gchar* _tmp4_;
		_tmp3_ = last_fm_core_getToken (self->priv->_lm->lfm);
		_tmp4_ = _tmp3_;
		_g_free0 (self->priv->lastfm_token);
		self->priv->lastfm_token = _tmp4_;
		if (self->priv->lastfm_token == NULL) {
			gtk_button_set_label (self->priv->lastfmLogin, "Unsuccessful. Click to try again.");
			fprintf (stdout, "Could not get a token. check internet connection\n");
		} else {
			gchar* auth_uri;
			auth_uri = g_strconcat ("http://www.last.fm/api/auth/?api_key=" LAST_FM_CORE_api "&token=", self->priv->lastfm_token, NULL);
			g_app_info_launch_default_for_uri (auth_uri, NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch62_g_error;
			}
			goto __finally62;
			__catch62_g_error:
			{
				GError * err;
				err = _inner_error_;
				_inner_error_ = NULL;
				fprintf (stdout, "Could not open Last FM website to authorize: %s\n", err->message);
				_g_error_free0 (err);
			}
			__finally62:
			if (_inner_error_ != NULL) {
				_g_free0 (auth_uri);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			gtk_button_set_label (self->priv->lastfmLogin, "Complete login");
			_g_free0 (auth_uri);
		}
	} else {
		if (self->priv->lastfm_token == NULL) {
			gtk_button_set_label (self->priv->lastfmLogin, "Unsuccessful. Click to try again.");
			fprintf (stdout, "Invalid token. Cannot continue\n");
		} else {
			gchar* _tmp5_ = NULL;
			gchar* sk;
			_tmp5_ = last_fm_core_getSessionKey (self->priv->_lm->lfm, self->priv->lastfm_token);
			sk = _tmp5_;
			if (sk == NULL) {
				gtk_button_set_label (self->priv->lastfmLogin, "Unsuccessful. Click to try again.");
				fprintf (stdout, "Could not get Last FM session key\n");
			} else {
				beat_box_settings_setLastFMSessionKey (self->priv->_lm->settings, sk);
				fprintf (stdout, "Successfully obtained a sessionkey\n");
				gtk_widget_set_sensitive ((GtkWidget*) self->priv->lastfmLogin, FALSE);
				gtk_button_set_label (self->priv->lastfmLogin, "Success!");
			}
			_g_free0 (sk);
		}
	}
}


void beat_box_preferences_window_lastfmLoginClick (BeatBoxPreferencesWindow* self) {
	BEAT_BOX_PREFERENCES_WINDOW_GET_CLASS (self)->lastfmLoginClick (self);
}


static void beat_box_preferences_window_real_saveClicked (BeatBoxPreferencesWindow* self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	gboolean _tmp4_;
	gboolean _tmp7_;
	gboolean _tmp8_;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_file_chooser_get_current_folder ((GtkFileChooser*) self->priv->fileChooser);
	_tmp1_ = _tmp0_;
	_tmp2_ = beat_box_settings_getMusicFolder (self->priv->_lm->settings);
	_tmp3_ = _tmp2_;
	if ((_tmp4_ = g_strcmp0 (_tmp1_, _tmp3_) != 0, _g_free0 (_tmp3_), _g_free0 (_tmp1_), _tmp4_)) {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_;
		_tmp5_ = gtk_file_chooser_get_current_folder ((GtkFileChooser*) self->priv->fileChooser);
		_tmp6_ = _tmp5_;
		g_signal_emit_by_name (self, "changed", _tmp6_);
		_g_free0 (_tmp6_);
	}
	_tmp7_ = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->organizeFolders);
	beat_box_settings_setUpdateFolderHierarchy (self->priv->_lm->settings, _tmp7_);
	_tmp8_ = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->copyImportedMusic);
	beat_box_settings_setCopyImportedMusic (self->priv->_lm->settings, _tmp8_);
	gtk_object_destroy ((GtkObject*) self);
}


void beat_box_preferences_window_saveClicked (BeatBoxPreferencesWindow* self) {
	BEAT_BOX_PREFERENCES_WINDOW_GET_CLASS (self)->saveClicked (self);
}


static void beat_box_preferences_window_real_cancelClicked (BeatBoxPreferencesWindow* self) {
	g_return_if_fail (self != NULL);
	gtk_object_destroy ((GtkObject*) self);
}


void beat_box_preferences_window_cancelClicked (BeatBoxPreferencesWindow* self) {
	BEAT_BOX_PREFERENCES_WINDOW_GET_CLASS (self)->cancelClicked (self);
}


static void beat_box_preferences_window_class_init (BeatBoxPreferencesWindowClass * klass) {
	beat_box_preferences_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (BeatBoxPreferencesWindowPrivate));
	BEAT_BOX_PREFERENCES_WINDOW_CLASS (klass)->lastfmLoginClick = beat_box_preferences_window_real_lastfmLoginClick;
	BEAT_BOX_PREFERENCES_WINDOW_CLASS (klass)->saveClicked = beat_box_preferences_window_real_saveClicked;
	BEAT_BOX_PREFERENCES_WINDOW_CLASS (klass)->cancelClicked = beat_box_preferences_window_real_cancelClicked;
	G_OBJECT_CLASS (klass)->finalize = beat_box_preferences_window_finalize;
	g_signal_new ("changed", BEAT_BOX_TYPE_PREFERENCES_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
}


static void beat_box_preferences_window_instance_init (BeatBoxPreferencesWindow * self) {
	self->priv = BEAT_BOX_PREFERENCES_WINDOW_GET_PRIVATE (self);
}


static void beat_box_preferences_window_finalize (GObject* obj) {
	BeatBoxPreferencesWindow * self;
	self = BEAT_BOX_PREFERENCES_WINDOW (obj);
	_g_object_unref0 (self->priv->_lm);
	_g_object_unref0 (self->priv->content);
	_g_object_unref0 (self->priv->padding);
	_g_object_unref0 (self->priv->musicLabel);
	_g_object_unref0 (self->priv->managementLabel);
	_g_object_unref0 (self->priv->lastfmLabel);
	_g_object_unref0 (self->priv->fileChooser);
	_g_object_unref0 (self->priv->organizeFolders);
	_g_object_unref0 (self->priv->copyImportedMusic);
	_g_object_unref0 (self->priv->lastfmLogin);
	_g_object_unref0 (self->priv->lastfmInfo);
	_g_object_unref0 (self->priv->saveChanges);
	_g_free0 (self->priv->lastfm_token);
	G_OBJECT_CLASS (beat_box_preferences_window_parent_class)->finalize (obj);
}


GType beat_box_preferences_window_get_type (void) {
	static volatile gsize beat_box_preferences_window_type_id__volatile = 0;
	if (g_once_init_enter (&beat_box_preferences_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BeatBoxPreferencesWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) beat_box_preferences_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BeatBoxPreferencesWindow), 0, (GInstanceInitFunc) beat_box_preferences_window_instance_init, NULL };
		GType beat_box_preferences_window_type_id;
		beat_box_preferences_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "BeatBoxPreferencesWindow", &g_define_type_info, 0);
		g_once_init_leave (&beat_box_preferences_window_type_id__volatile, beat_box_preferences_window_type_id);
	}
	return beat_box_preferences_window_type_id__volatile;
}



