/* SongEditor.c generated by valac 0.11.6, the Vala compiler
 * generated from SongEditor.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define BEAT_BOX_TYPE_SONG_EDITOR (beat_box_song_editor_get_type ())
#define BEAT_BOX_SONG_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_SONG_EDITOR, BeatBoxSongEditor))
#define BEAT_BOX_SONG_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_SONG_EDITOR, BeatBoxSongEditorClass))
#define BEAT_BOX_IS_SONG_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_SONG_EDITOR))
#define BEAT_BOX_IS_SONG_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_SONG_EDITOR))
#define BEAT_BOX_SONG_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_SONG_EDITOR, BeatBoxSongEditorClass))

typedef struct _BeatBoxSongEditor BeatBoxSongEditor;
typedef struct _BeatBoxSongEditorClass BeatBoxSongEditorClass;
typedef struct _BeatBoxSongEditorPrivate BeatBoxSongEditorPrivate;

#define BEAT_BOX_TYPE_SONG (beat_box_song_get_type ())
#define BEAT_BOX_SONG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_SONG, BeatBoxSong))
#define BEAT_BOX_SONG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_SONG, BeatBoxSongClass))
#define BEAT_BOX_IS_SONG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_SONG))
#define BEAT_BOX_IS_SONG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_SONG))
#define BEAT_BOX_SONG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_SONG, BeatBoxSongClass))

typedef struct _BeatBoxSong BeatBoxSong;
typedef struct _BeatBoxSongClass BeatBoxSongClass;

#define BEAT_BOX_TYPE_FIELD_EDITOR (beat_box_field_editor_get_type ())
#define BEAT_BOX_FIELD_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_FIELD_EDITOR, BeatBoxFieldEditor))
#define BEAT_BOX_FIELD_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_FIELD_EDITOR, BeatBoxFieldEditorClass))
#define BEAT_BOX_IS_FIELD_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_FIELD_EDITOR))
#define BEAT_BOX_IS_FIELD_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_FIELD_EDITOR))
#define BEAT_BOX_FIELD_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_FIELD_EDITOR, BeatBoxFieldEditorClass))

typedef struct _BeatBoxFieldEditor BeatBoxFieldEditor;
typedef struct _BeatBoxFieldEditorClass BeatBoxFieldEditorClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define LAST_FM_TYPE_TRACK_INFO (last_fm_track_info_get_type ())
#define LAST_FM_TRACK_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAST_FM_TYPE_TRACK_INFO, LastFMTrackInfo))
#define LAST_FM_TRACK_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAST_FM_TYPE_TRACK_INFO, LastFMTrackInfoClass))
#define LAST_FM_IS_TRACK_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAST_FM_TYPE_TRACK_INFO))
#define LAST_FM_IS_TRACK_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAST_FM_TYPE_TRACK_INFO))
#define LAST_FM_TRACK_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAST_FM_TYPE_TRACK_INFO, LastFMTrackInfoClass))

typedef struct _LastFMTrackInfo LastFMTrackInfo;
typedef struct _LastFMTrackInfoClass LastFMTrackInfoClass;

#define LAST_FM_TYPE_ARTIST_INFO (last_fm_artist_info_get_type ())
#define LAST_FM_ARTIST_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAST_FM_TYPE_ARTIST_INFO, LastFMArtistInfo))
#define LAST_FM_ARTIST_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAST_FM_TYPE_ARTIST_INFO, LastFMArtistInfoClass))
#define LAST_FM_IS_ARTIST_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAST_FM_TYPE_ARTIST_INFO))
#define LAST_FM_IS_ARTIST_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAST_FM_TYPE_ARTIST_INFO))
#define LAST_FM_ARTIST_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAST_FM_TYPE_ARTIST_INFO, LastFMArtistInfoClass))

typedef struct _LastFMArtistInfo LastFMArtistInfo;
typedef struct _LastFMArtistInfoClass LastFMArtistInfoClass;

#define LAST_FM_TYPE_ALBUM_INFO (last_fm_album_info_get_type ())
#define LAST_FM_ALBUM_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAST_FM_TYPE_ALBUM_INFO, LastFMAlbumInfo))
#define LAST_FM_ALBUM_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAST_FM_TYPE_ALBUM_INFO, LastFMAlbumInfoClass))
#define LAST_FM_IS_ALBUM_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAST_FM_TYPE_ALBUM_INFO))
#define LAST_FM_IS_ALBUM_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAST_FM_TYPE_ALBUM_INFO))
#define LAST_FM_ALBUM_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAST_FM_TYPE_ALBUM_INFO, LastFMAlbumInfoClass))

typedef struct _LastFMAlbumInfo LastFMAlbumInfo;
typedef struct _LastFMAlbumInfoClass LastFMAlbumInfoClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _BeatBoxFieldEditorPrivate BeatBoxFieldEditorPrivate;

struct _BeatBoxSongEditor {
	GtkWindow parent_instance;
	BeatBoxSongEditorPrivate * priv;
};

struct _BeatBoxSongEditorClass {
	GtkWindowClass parent_class;
	void (*saveClicked) (BeatBoxSongEditor* self);
};

struct _BeatBoxSongEditorPrivate {
	GeeLinkedList* _songs;
	GtkVBox* content;
	GtkHBox* padding;
	GtkNotebook* notebook;
	GtkViewport* editView;
	GtkVBox* vert;
	GtkHBox* horiz;
	GtkVBox* textVert;
	GtkVBox* numerVert;
	GeeHashMap* fields;
	GtkButton* _save;
};

struct _BeatBoxFieldEditor {
	GtkHBox parent_instance;
	BeatBoxFieldEditorPrivate * priv;
};

struct _BeatBoxFieldEditorClass {
	GtkHBoxClass parent_class;
	void (*entryChanged) (BeatBoxFieldEditor* self);
	void (*textViewChanged) (BeatBoxFieldEditor* self);
	void (*spinButtonChanged) (BeatBoxFieldEditor* self);
	void (*resetClicked) (BeatBoxFieldEditor* self);
};

struct _BeatBoxFieldEditorPrivate {
	gchar* _name;
	gchar* _original;
	GtkCheckButton* check;
	GtkLabel* label;
	GtkEntry* entry;
	GtkTextView* textView;
	GtkSpinButton* spinButton;
	GtkImage* image;
	GtkButton* reset;
};


static gpointer beat_box_song_editor_parent_class = NULL;
static gpointer beat_box_field_editor_parent_class = NULL;

GType beat_box_song_editor_get_type (void) G_GNUC_CONST;
GType beat_box_song_get_type (void) G_GNUC_CONST;
GType beat_box_field_editor_get_type (void) G_GNUC_CONST;
#define BEAT_BOX_SONG_EDITOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), BEAT_BOX_TYPE_SONG_EDITOR, BeatBoxSongEditorPrivate))
enum  {
	BEAT_BOX_SONG_EDITOR_DUMMY_PROPERTY
};
GType last_fm_track_info_get_type (void) G_GNUC_CONST;
GType last_fm_artist_info_get_type (void) G_GNUC_CONST;
GType last_fm_album_info_get_type (void) G_GNUC_CONST;
BeatBoxSongEditor* beat_box_song_editor_new (GeeLinkedList* songs, LastFMTrackInfo* track, LastFMArtistInfo* artist, LastFMAlbumInfo* album);
BeatBoxSongEditor* beat_box_song_editor_construct (GType object_type, GeeLinkedList* songs, LastFMTrackInfo* track, LastFMArtistInfo* artist, LastFMAlbumInfo* album);
BeatBoxSong* beat_box_song_copy (BeatBoxSong* self);
gint beat_box_song_get_track (BeatBoxSong* self);
void beat_box_song_set_track (BeatBoxSong* self, gint value);
const gchar* beat_box_song_get_title (BeatBoxSong* self);
void beat_box_song_set_title (BeatBoxSong* self, const gchar* value);
const gchar* beat_box_song_get_artist (BeatBoxSong* self);
void beat_box_song_set_artist (BeatBoxSong* self, const gchar* value);
const gchar* beat_box_song_get_album (BeatBoxSong* self);
void beat_box_song_set_album (BeatBoxSong* self, const gchar* value);
const gchar* beat_box_song_get_genre (BeatBoxSong* self);
void beat_box_song_set_genre (BeatBoxSong* self, const gchar* value);
const gchar* beat_box_song_get_comment (BeatBoxSong* self);
void beat_box_song_set_comment (BeatBoxSong* self, const gchar* value);
gint beat_box_song_get_year (BeatBoxSong* self);
void beat_box_song_set_year (BeatBoxSong* self, gint value);
gint beat_box_song_get_bitrate (BeatBoxSong* self);
void beat_box_song_set_bitrate (BeatBoxSong* self, gint value);
gint beat_box_song_get_bpm (BeatBoxSong* self);
void beat_box_song_set_bpm (BeatBoxSong* self, gint value);
gint beat_box_song_get_rating (BeatBoxSong* self);
void beat_box_song_set_rating (BeatBoxSong* self, gint value);
BeatBoxFieldEditor* beat_box_field_editor_new (const gchar* name, const gchar* original, GtkWidget* w);
BeatBoxFieldEditor* beat_box_field_editor_construct (GType object_type, const gchar* name, const gchar* original, GtkWidget* w);
GtkViewport* beat_box_song_editor_generate_track_page (BeatBoxSongEditor* self, LastFMTrackInfo* track);
GtkViewport* beat_box_song_editor_generate_artist_page (BeatBoxSongEditor* self, LastFMArtistInfo* artist);
GtkViewport* beat_box_song_editor_generate_album_page (BeatBoxSongEditor* self, LastFMAlbumInfo* album);
GtkAlignment* beat_box_song_editor_wrap_alignment (GtkWidget* widget, gint top, gint right, gint bottom, gint left);
void beat_box_field_editor_set_check_visible (BeatBoxFieldEditor* self, gboolean val);
void beat_box_song_editor_saveClicked (BeatBoxSongEditor* self);
static void _beat_box_song_editor_saveClicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
const gchar* last_fm_track_info_get_name (LastFMTrackInfo* self);
const gchar* last_fm_track_info_get_url (LastFMTrackInfo* self);
const gchar* last_fm_track_info_get_artist (LastFMTrackInfo* self);
const gchar* last_fm_artist_info_get_name (LastFMArtistInfo* self);
const gchar* last_fm_artist_info_get_url (LastFMArtistInfo* self);
const gchar* last_fm_album_info_get_name (LastFMAlbumInfo* self);
static void beat_box_song_editor_real_saveClicked (BeatBoxSongEditor* self);
gboolean beat_box_field_editor_checked (BeatBoxFieldEditor* self);
gchar* beat_box_field_editor_get_value (BeatBoxFieldEditor* self);
static void beat_box_song_editor_finalize (GObject* obj);
#define BEAT_BOX_FIELD_EDITOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), BEAT_BOX_TYPE_FIELD_EDITOR, BeatBoxFieldEditorPrivate))
enum  {
	BEAT_BOX_FIELD_EDITOR_DUMMY_PROPERTY
};
void beat_box_field_editor_entryChanged (BeatBoxFieldEditor* self);
static void _beat_box_field_editor_entryChanged_gtk_editable_changed (GtkEditable* _sender, gpointer self);
void beat_box_field_editor_textViewChanged (BeatBoxFieldEditor* self);
static void _beat_box_field_editor_textViewChanged_gtk_text_buffer_changed (GtkTextBuffer* _sender, gpointer self);
void beat_box_field_editor_spinButtonChanged (BeatBoxFieldEditor* self);
static void _beat_box_field_editor_spinButtonChanged_gtk_adjustment_value_changed (GtkAdjustment* _sender, gpointer self);
void beat_box_field_editor_resetClicked (BeatBoxFieldEditor* self);
static void _beat_box_field_editor_resetClicked_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void beat_box_field_editor_real_entryChanged (BeatBoxFieldEditor* self);
static void beat_box_field_editor_real_textViewChanged (BeatBoxFieldEditor* self);
static void beat_box_field_editor_real_spinButtonChanged (BeatBoxFieldEditor* self);
static void beat_box_field_editor_real_resetClicked (BeatBoxFieldEditor* self);
static void beat_box_field_editor_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _beat_box_song_editor_saveClicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	beat_box_song_editor_saveClicked (self);
}


BeatBoxSongEditor* beat_box_song_editor_construct (GType object_type, GeeLinkedList* songs, LastFMTrackInfo* track, LastFMArtistInfo* artist, LastFMAlbumInfo* album) {
	BeatBoxSongEditor * self = NULL;
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* _tmp1_;
	GeeLinkedList* _tmp2_;
	GeeLinkedList* _tmp3_;
	gpointer _tmp4_ = NULL;
	BeatBoxSong* _tmp5_;
	BeatBoxSong* _tmp6_ = NULL;
	BeatBoxSong* _tmp7_;
	BeatBoxSong* sum;
	const gchar* _tmp31_ = NULL;
	GtkEntry* _tmp32_ = NULL;
	GtkEntry* _tmp33_;
	BeatBoxFieldEditor* _tmp34_ = NULL;
	BeatBoxFieldEditor* _tmp35_;
	const gchar* _tmp36_ = NULL;
	GtkEntry* _tmp37_ = NULL;
	GtkEntry* _tmp38_;
	BeatBoxFieldEditor* _tmp39_ = NULL;
	BeatBoxFieldEditor* _tmp40_;
	const gchar* _tmp41_ = NULL;
	GtkEntry* _tmp42_ = NULL;
	GtkEntry* _tmp43_;
	BeatBoxFieldEditor* _tmp44_ = NULL;
	BeatBoxFieldEditor* _tmp45_;
	const gchar* _tmp46_ = NULL;
	GtkEntry* _tmp47_ = NULL;
	GtkEntry* _tmp48_;
	BeatBoxFieldEditor* _tmp49_ = NULL;
	BeatBoxFieldEditor* _tmp50_;
	const gchar* _tmp51_ = NULL;
	GtkTextView* _tmp52_ = NULL;
	GtkTextView* _tmp53_;
	BeatBoxFieldEditor* _tmp54_ = NULL;
	BeatBoxFieldEditor* _tmp55_;
	gint _tmp56_;
	gchar* _tmp57_ = NULL;
	gchar* _tmp58_;
	GtkSpinButton* _tmp59_ = NULL;
	GtkSpinButton* _tmp60_;
	BeatBoxFieldEditor* _tmp61_ = NULL;
	BeatBoxFieldEditor* _tmp62_;
	gint _tmp63_;
	gchar* _tmp64_ = NULL;
	gchar* _tmp65_;
	GtkSpinButton* _tmp66_ = NULL;
	GtkSpinButton* _tmp67_;
	BeatBoxFieldEditor* _tmp68_ = NULL;
	BeatBoxFieldEditor* _tmp69_;
	GtkVBox* _tmp70_ = NULL;
	GtkVBox* _tmp71_;
	GtkHBox* _tmp72_ = NULL;
	GtkHBox* _tmp73_;
	GtkNotebook* _tmp74_ = NULL;
	GtkNotebook* _tmp75_;
	GtkViewport* _tmp76_ = NULL;
	GtkViewport* _tmp77_;
	GtkVBox* _tmp78_ = NULL;
	GtkVBox* _tmp79_;
	GtkHBox* _tmp80_ = NULL;
	GtkHBox* _tmp81_;
	GtkVBox* _tmp82_ = NULL;
	GtkVBox* _tmp83_;
	GtkVBox* _tmp84_ = NULL;
	GtkVBox* _tmp85_;
	gpointer _tmp86_ = NULL;
	BeatBoxFieldEditor* _tmp87_;
	gpointer _tmp88_ = NULL;
	BeatBoxFieldEditor* _tmp89_;
	gpointer _tmp90_ = NULL;
	BeatBoxFieldEditor* _tmp91_;
	gpointer _tmp92_ = NULL;
	BeatBoxFieldEditor* _tmp93_;
	gpointer _tmp94_ = NULL;
	BeatBoxFieldEditor* _tmp95_;
	gpointer _tmp96_ = NULL;
	BeatBoxFieldEditor* _tmp97_;
	gpointer _tmp98_ = NULL;
	BeatBoxFieldEditor* _tmp99_;
	GtkHButtonBox* _tmp100_ = NULL;
	GtkHButtonBox* buttonSep;
	GtkButton* _tmp101_ = NULL;
	GtkButton* _tmp102_;
	GtkLabel* _tmp103_ = NULL;
	GtkLabel* _tmp104_;
	GtkAlignment* _tmp117_ = NULL;
	GtkAlignment* _tmp118_;
	GtkAlignment* _tmp119_ = NULL;
	GtkAlignment* _tmp120_;
	gint _tmp121_;
	g_return_val_if_fail (songs != NULL, NULL);
	self = (BeatBoxSongEditor*) g_object_new (object_type, NULL);
	gtk_window_set_title ((GtkWindow*) self, "Properties");
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, BEAT_BOX_TYPE_FIELD_EDITOR, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_tmp1_ = _tmp0_;
	_g_object_unref0 (self->priv->fields);
	self->priv->fields = _tmp1_;
	_tmp2_ = _g_object_ref0 (songs);
	_tmp3_ = _tmp2_;
	_g_object_unref0 (self->priv->_songs);
	self->priv->_songs = _tmp3_;
	_tmp4_ = gee_abstract_list_get ((GeeAbstractList*) songs, 0);
	_tmp5_ = (BeatBoxSong*) _tmp4_;
	_tmp6_ = beat_box_song_copy (_tmp5_);
	sum = (_tmp7_ = _tmp6_, _g_object_unref0 (_tmp5_), _tmp7_);
	{
		GeeLinkedList* _tmp8_;
		GeeLinkedList* _s_list;
		gint _tmp9_;
		gint _s_size;
		gint _s_index;
		_tmp8_ = _g_object_ref0 (songs);
		_s_list = _tmp8_;
		_tmp9_ = gee_collection_get_size ((GeeCollection*) _s_list);
		_s_size = _tmp9_;
		_s_index = -1;
		while (TRUE) {
			gpointer _tmp10_ = NULL;
			BeatBoxSong* s;
			gint _tmp11_;
			gint _tmp12_;
			const gchar* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
			const gchar* _tmp15_ = NULL;
			const gchar* _tmp16_ = NULL;
			const gchar* _tmp17_ = NULL;
			const gchar* _tmp18_ = NULL;
			const gchar* _tmp19_ = NULL;
			const gchar* _tmp20_ = NULL;
			const gchar* _tmp21_ = NULL;
			const gchar* _tmp22_ = NULL;
			gint _tmp23_;
			gint _tmp24_;
			gint _tmp25_;
			gint _tmp26_;
			gint _tmp27_;
			gint _tmp28_;
			gint _tmp29_;
			gint _tmp30_;
			_s_index = _s_index + 1;
			if (!(_s_index < _s_size)) {
				break;
			}
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _s_list, _s_index);
			s = (BeatBoxSong*) _tmp10_;
			_tmp11_ = beat_box_song_get_track (s);
			_tmp12_ = beat_box_song_get_track (sum);
			if (_tmp11_ != _tmp12_) {
				beat_box_song_set_track (sum, -1);
			}
			_tmp13_ = beat_box_song_get_title (s);
			_tmp14_ = beat_box_song_get_title (sum);
			if (g_strcmp0 (_tmp13_, _tmp14_) != 0) {
				beat_box_song_set_title (sum, "");
			}
			_tmp15_ = beat_box_song_get_artist (s);
			_tmp16_ = beat_box_song_get_artist (sum);
			if (g_strcmp0 (_tmp15_, _tmp16_) != 0) {
				beat_box_song_set_artist (sum, "");
			}
			_tmp17_ = beat_box_song_get_album (s);
			_tmp18_ = beat_box_song_get_album (sum);
			if (g_strcmp0 (_tmp17_, _tmp18_) != 0) {
				beat_box_song_set_album (sum, "");
			}
			_tmp19_ = beat_box_song_get_genre (s);
			_tmp20_ = beat_box_song_get_genre (sum);
			if (g_strcmp0 (_tmp19_, _tmp20_) != 0) {
				beat_box_song_set_genre (sum, "");
			}
			_tmp21_ = beat_box_song_get_comment (s);
			_tmp22_ = beat_box_song_get_comment (sum);
			if (g_strcmp0 (_tmp21_, _tmp22_) != 0) {
				beat_box_song_set_comment (sum, "");
			}
			_tmp23_ = beat_box_song_get_year (s);
			_tmp24_ = beat_box_song_get_year (sum);
			if (_tmp23_ != _tmp24_) {
				beat_box_song_set_year (sum, -1);
			}
			_tmp25_ = beat_box_song_get_bitrate (s);
			_tmp26_ = beat_box_song_get_bitrate (sum);
			if (_tmp25_ != _tmp26_) {
				beat_box_song_set_bitrate (sum, -1);
			}
			_tmp27_ = beat_box_song_get_bpm (s);
			_tmp28_ = beat_box_song_get_bpm (sum);
			if (_tmp27_ != _tmp28_) {
				beat_box_song_set_bpm (sum, -1);
			}
			_tmp29_ = beat_box_song_get_rating (s);
			_tmp30_ = beat_box_song_get_rating (sum);
			if (_tmp29_ != _tmp30_) {
				beat_box_song_set_rating (sum, -1);
			}
			_g_object_unref0 (s);
		}
		_g_object_unref0 (_s_list);
	}
	_tmp31_ = beat_box_song_get_title (sum);
	_tmp32_ = (GtkEntry*) gtk_entry_new ();
	_tmp33_ = g_object_ref_sink (_tmp32_);
	_tmp34_ = beat_box_field_editor_new ("Title", _tmp31_, (GtkWidget*) _tmp33_);
	_tmp35_ = g_object_ref_sink (_tmp34_);
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->fields, "Title", _tmp35_);
	_g_object_unref0 (_tmp35_);
	_g_object_unref0 (_tmp33_);
	_tmp36_ = beat_box_song_get_artist (sum);
	_tmp37_ = (GtkEntry*) gtk_entry_new ();
	_tmp38_ = g_object_ref_sink (_tmp37_);
	_tmp39_ = beat_box_field_editor_new ("Artist", _tmp36_, (GtkWidget*) _tmp38_);
	_tmp40_ = g_object_ref_sink (_tmp39_);
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->fields, "Artist", _tmp40_);
	_g_object_unref0 (_tmp40_);
	_g_object_unref0 (_tmp38_);
	_tmp41_ = beat_box_song_get_album (sum);
	_tmp42_ = (GtkEntry*) gtk_entry_new ();
	_tmp43_ = g_object_ref_sink (_tmp42_);
	_tmp44_ = beat_box_field_editor_new ("Album", _tmp41_, (GtkWidget*) _tmp43_);
	_tmp45_ = g_object_ref_sink (_tmp44_);
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->fields, "Album", _tmp45_);
	_g_object_unref0 (_tmp45_);
	_g_object_unref0 (_tmp43_);
	_tmp46_ = beat_box_song_get_genre (sum);
	_tmp47_ = (GtkEntry*) gtk_entry_new ();
	_tmp48_ = g_object_ref_sink (_tmp47_);
	_tmp49_ = beat_box_field_editor_new ("Genre", _tmp46_, (GtkWidget*) _tmp48_);
	_tmp50_ = g_object_ref_sink (_tmp49_);
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->fields, "Genre", _tmp50_);
	_g_object_unref0 (_tmp50_);
	_g_object_unref0 (_tmp48_);
	_tmp51_ = beat_box_song_get_comment (sum);
	_tmp52_ = (GtkTextView*) gtk_text_view_new ();
	_tmp53_ = g_object_ref_sink (_tmp52_);
	_tmp54_ = beat_box_field_editor_new ("Comment", _tmp51_, (GtkWidget*) _tmp53_);
	_tmp55_ = g_object_ref_sink (_tmp54_);
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->fields, "Comment", _tmp55_);
	_g_object_unref0 (_tmp55_);
	_g_object_unref0 (_tmp53_);
	_tmp56_ = beat_box_song_get_track (sum);
	_tmp57_ = g_strdup_printf ("%i", _tmp56_);
	_tmp58_ = _tmp57_;
	_tmp59_ = (GtkSpinButton*) gtk_spin_button_new_with_range ((gdouble) 0, (gdouble) 100, (gdouble) 1);
	_tmp60_ = g_object_ref_sink (_tmp59_);
	_tmp61_ = beat_box_field_editor_new ("Track", _tmp58_, (GtkWidget*) _tmp60_);
	_tmp62_ = g_object_ref_sink (_tmp61_);
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->fields, "Track", _tmp62_);
	_g_object_unref0 (_tmp62_);
	_g_object_unref0 (_tmp60_);
	_g_free0 (_tmp58_);
	_tmp63_ = beat_box_song_get_year (sum);
	_tmp64_ = g_strdup_printf ("%i", _tmp63_);
	_tmp65_ = _tmp64_;
	_tmp66_ = (GtkSpinButton*) gtk_spin_button_new_with_range ((gdouble) 1000, (gdouble) 9999, (gdouble) 1);
	_tmp67_ = g_object_ref_sink (_tmp66_);
	_tmp68_ = beat_box_field_editor_new ("Year", _tmp65_, (GtkWidget*) _tmp67_);
	_tmp69_ = g_object_ref_sink (_tmp68_);
	gee_abstract_map_set ((GeeAbstractMap*) self->priv->fields, "Year", _tmp69_);
	_g_object_unref0 (_tmp69_);
	_g_object_unref0 (_tmp67_);
	_g_free0 (_tmp65_);
	_tmp70_ = (GtkVBox*) gtk_vbox_new (FALSE, 10);
	_tmp71_ = g_object_ref_sink (_tmp70_);
	_g_object_unref0 (self->priv->content);
	self->priv->content = _tmp71_;
	_tmp72_ = (GtkHBox*) gtk_hbox_new (FALSE, 10);
	_tmp73_ = g_object_ref_sink (_tmp72_);
	_g_object_unref0 (self->priv->padding);
	self->priv->padding = _tmp73_;
	_tmp74_ = (GtkNotebook*) gtk_notebook_new ();
	_tmp75_ = g_object_ref_sink (_tmp74_);
	_g_object_unref0 (self->priv->notebook);
	self->priv->notebook = _tmp75_;
	_tmp76_ = (GtkViewport*) gtk_viewport_new (NULL, NULL);
	_tmp77_ = g_object_ref_sink (_tmp76_);
	_g_object_unref0 (self->priv->editView);
	self->priv->editView = _tmp77_;
	_tmp78_ = (GtkVBox*) gtk_vbox_new (FALSE, 0);
	_tmp79_ = g_object_ref_sink (_tmp78_);
	_g_object_unref0 (self->priv->vert);
	self->priv->vert = _tmp79_;
	_tmp80_ = (GtkHBox*) gtk_hbox_new (FALSE, 0);
	_tmp81_ = g_object_ref_sink (_tmp80_);
	_g_object_unref0 (self->priv->horiz);
	self->priv->horiz = _tmp81_;
	_tmp82_ = (GtkVBox*) gtk_vbox_new (FALSE, 0);
	_tmp83_ = g_object_ref_sink (_tmp82_);
	_g_object_unref0 (self->priv->textVert);
	self->priv->textVert = _tmp83_;
	_tmp84_ = (GtkVBox*) gtk_vbox_new (FALSE, 0);
	_tmp85_ = g_object_ref_sink (_tmp84_);
	_g_object_unref0 (self->priv->numerVert);
	self->priv->numerVert = _tmp85_;
	_tmp86_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Title");
	_tmp87_ = (BeatBoxFieldEditor*) _tmp86_;
	gtk_box_pack_start ((GtkBox*) self->priv->textVert, (GtkWidget*) _tmp87_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp87_);
	_tmp88_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Artist");
	_tmp89_ = (BeatBoxFieldEditor*) _tmp88_;
	gtk_box_pack_start ((GtkBox*) self->priv->textVert, (GtkWidget*) _tmp89_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp89_);
	_tmp90_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Album");
	_tmp91_ = (BeatBoxFieldEditor*) _tmp90_;
	gtk_box_pack_start ((GtkBox*) self->priv->textVert, (GtkWidget*) _tmp91_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp91_);
	_tmp92_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Genre");
	_tmp93_ = (BeatBoxFieldEditor*) _tmp92_;
	gtk_box_pack_start ((GtkBox*) self->priv->textVert, (GtkWidget*) _tmp93_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp93_);
	_tmp94_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Comment");
	_tmp95_ = (BeatBoxFieldEditor*) _tmp94_;
	gtk_box_pack_start ((GtkBox*) self->priv->textVert, (GtkWidget*) _tmp95_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp95_);
	_tmp96_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Track");
	_tmp97_ = (BeatBoxFieldEditor*) _tmp96_;
	gtk_box_pack_start ((GtkBox*) self->priv->numerVert, (GtkWidget*) _tmp97_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp97_);
	_tmp98_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Year");
	_tmp99_ = (BeatBoxFieldEditor*) _tmp98_;
	gtk_box_pack_start ((GtkBox*) self->priv->numerVert, (GtkWidget*) _tmp99_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp99_);
	gtk_box_pack_start ((GtkBox*) self->priv->horiz, (GtkWidget*) self->priv->textVert, FALSE, TRUE, (guint) 0);
	gtk_box_pack_end ((GtkBox*) self->priv->horiz, (GtkWidget*) self->priv->numerVert, FALSE, TRUE, (guint) 0);
	gtk_box_pack_start ((GtkBox*) self->priv->vert, (GtkWidget*) self->priv->horiz, TRUE, TRUE, (guint) 0);
	_tmp100_ = (GtkHButtonBox*) gtk_hbutton_box_new ();
	buttonSep = g_object_ref_sink (_tmp100_);
	gtk_button_box_set_layout ((GtkButtonBox*) buttonSep, GTK_BUTTONBOX_END);
	_tmp101_ = (GtkButton*) gtk_button_new_with_label ("Done");
	_tmp102_ = g_object_ref_sink (_tmp101_);
	_g_object_unref0 (self->priv->_save);
	self->priv->_save = _tmp102_;
	gtk_box_pack_end ((GtkBox*) buttonSep, (GtkWidget*) self->priv->_save, FALSE, FALSE, (guint) 0);
	gtk_container_add ((GtkContainer*) self->priv->editView, (GtkWidget*) self->priv->vert);
	_tmp103_ = (GtkLabel*) gtk_label_new ("Properties");
	_tmp104_ = g_object_ref_sink (_tmp103_);
	gtk_notebook_append_page (self->priv->notebook, (GtkWidget*) self->priv->editView, (GtkWidget*) _tmp104_);
	_g_object_unref0 (_tmp104_);
	if (track != NULL) {
		GtkViewport* _tmp105_ = NULL;
		GtkViewport* _tmp106_;
		GtkLabel* _tmp107_ = NULL;
		GtkLabel* _tmp108_;
		_tmp105_ = beat_box_song_editor_generate_track_page (self, track);
		_tmp106_ = _tmp105_;
		_tmp107_ = (GtkLabel*) gtk_label_new ("Track Info");
		_tmp108_ = g_object_ref_sink (_tmp107_);
		gtk_notebook_append_page (self->priv->notebook, (GtkWidget*) _tmp106_, (GtkWidget*) _tmp108_);
		_g_object_unref0 (_tmp108_);
		_g_object_unref0 (_tmp106_);
	}
	if (artist != NULL) {
		GtkViewport* _tmp109_ = NULL;
		GtkViewport* _tmp110_;
		GtkLabel* _tmp111_ = NULL;
		GtkLabel* _tmp112_;
		_tmp109_ = beat_box_song_editor_generate_artist_page (self, artist);
		_tmp110_ = _tmp109_;
		_tmp111_ = (GtkLabel*) gtk_label_new ("Artist Info");
		_tmp112_ = g_object_ref_sink (_tmp111_);
		gtk_notebook_append_page (self->priv->notebook, (GtkWidget*) _tmp110_, (GtkWidget*) _tmp112_);
		_g_object_unref0 (_tmp112_);
		_g_object_unref0 (_tmp110_);
	}
	if (album != NULL) {
		GtkViewport* _tmp113_ = NULL;
		GtkViewport* _tmp114_;
		GtkLabel* _tmp115_ = NULL;
		GtkLabel* _tmp116_;
		_tmp113_ = beat_box_song_editor_generate_album_page (self, album);
		_tmp114_ = _tmp113_;
		_tmp115_ = (GtkLabel*) gtk_label_new ("Album Info");
		_tmp116_ = g_object_ref_sink (_tmp115_);
		gtk_notebook_append_page (self->priv->notebook, (GtkWidget*) _tmp114_, (GtkWidget*) _tmp116_);
		_g_object_unref0 (_tmp116_);
		_g_object_unref0 (_tmp114_);
	}
	_tmp117_ = beat_box_song_editor_wrap_alignment ((GtkWidget*) self->priv->notebook, 10, 0, 0, 0);
	_tmp118_ = _tmp117_;
	gtk_box_pack_start ((GtkBox*) self->priv->content, (GtkWidget*) _tmp118_, TRUE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp118_);
	_tmp119_ = beat_box_song_editor_wrap_alignment ((GtkWidget*) buttonSep, 0, 0, 10, 0);
	_tmp120_ = _tmp119_;
	gtk_box_pack_start ((GtkBox*) self->priv->content, (GtkWidget*) _tmp120_, FALSE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp120_);
	gtk_box_pack_start ((GtkBox*) self->priv->padding, (GtkWidget*) self->priv->content, TRUE, TRUE, (guint) 10);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->priv->padding);
	gtk_widget_show_all ((GtkWidget*) self);
	_tmp121_ = gee_collection_get_size ((GeeCollection*) self->priv->_songs);
	if (_tmp121_ == 1) {
		{
			GeeCollection* _tmp122_ = NULL;
			GeeCollection* _tmp123_;
			GeeIterator* _tmp124_ = NULL;
			GeeIterator* _tmp125_;
			GeeIterator* _fe_it;
			_tmp122_ = gee_map_get_values ((GeeMap*) self->priv->fields);
			_tmp123_ = _tmp122_;
			_tmp124_ = gee_iterable_iterator ((GeeIterable*) _tmp123_);
			_fe_it = (_tmp125_ = _tmp124_, _g_object_unref0 (_tmp123_), _tmp125_);
			while (TRUE) {
				gboolean _tmp126_;
				gpointer _tmp127_ = NULL;
				BeatBoxFieldEditor* fe;
				_tmp126_ = gee_iterator_next (_fe_it);
				if (!_tmp126_) {
					break;
				}
				_tmp127_ = gee_iterator_get (_fe_it);
				fe = (BeatBoxFieldEditor*) _tmp127_;
				beat_box_field_editor_set_check_visible (fe, FALSE);
				_g_object_unref0 (fe);
			}
			_g_object_unref0 (_fe_it);
		}
	}
	g_signal_connect_object (self->priv->_save, "clicked", (GCallback) _beat_box_song_editor_saveClicked_gtk_button_clicked, self, 0);
	_g_object_unref0 (buttonSep);
	_g_object_unref0 (sum);
	return self;
}


BeatBoxSongEditor* beat_box_song_editor_new (GeeLinkedList* songs, LastFMTrackInfo* track, LastFMArtistInfo* artist, LastFMAlbumInfo* album) {
	return beat_box_song_editor_construct (BEAT_BOX_TYPE_SONG_EDITOR, songs, track, artist, album);
}


GtkAlignment* beat_box_song_editor_wrap_alignment (GtkWidget* widget, gint top, gint right, gint bottom, gint left) {
	GtkAlignment* result = NULL;
	GtkAlignment* _tmp0_ = NULL;
	GtkAlignment* alignment;
	g_return_val_if_fail (widget != NULL, NULL);
	_tmp0_ = (GtkAlignment*) gtk_alignment_new (0.0f, 0.0f, 1.0f, 1.0f);
	alignment = g_object_ref_sink (_tmp0_);
	g_object_set (alignment, "top-padding", (guint) top, NULL);
	g_object_set (alignment, "right-padding", (guint) right, NULL);
	g_object_set (alignment, "bottom-padding", (guint) bottom, NULL);
	g_object_set (alignment, "left-padding", (guint) left, NULL);
	gtk_container_add ((GtkContainer*) alignment, widget);
	result = alignment;
	return result;
}


GtkViewport* beat_box_song_editor_generate_track_page (BeatBoxSongEditor* self, LastFMTrackInfo* track) {
	GtkViewport* result = NULL;
	GtkViewport* _tmp0_ = NULL;
	GtkViewport* rv;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	gchar* _tmp5_;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	GtkLabel* _tmp8_ = NULL;
	GtkLabel* _tmp9_;
	GtkLabel* l;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (track != NULL, NULL);
	_tmp0_ = (GtkViewport*) gtk_viewport_new (NULL, NULL);
	rv = g_object_ref_sink (_tmp0_);
	_tmp1_ = last_fm_track_info_get_name (track);
	_tmp2_ = g_strconcat (_tmp1_, ",", NULL);
	_tmp3_ = last_fm_track_info_get_url (track);
	_tmp4_ = g_strconcat (_tmp2_, _tmp3_, NULL);
	_tmp5_ = g_strconcat (_tmp4_, ",", NULL);
	_tmp6_ = last_fm_track_info_get_artist (track);
	_tmp7_ = g_strconcat (_tmp5_, _tmp6_, NULL);
	_tmp8_ = (GtkLabel*) gtk_label_new (_tmp7_);
	l = (_tmp9_ = g_object_ref_sink (_tmp8_), _g_free0 (_tmp7_), _g_free0 (_tmp5_), _g_free0 (_tmp4_), _g_free0 (_tmp2_), _tmp9_);
	gtk_container_add ((GtkContainer*) rv, (GtkWidget*) l);
	result = rv;
	_g_object_unref0 (l);
	return result;
}


GtkViewport* beat_box_song_editor_generate_artist_page (BeatBoxSongEditor* self, LastFMArtistInfo* artist) {
	GtkViewport* result = NULL;
	GtkViewport* _tmp0_ = NULL;
	GtkViewport* rv;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	GtkLabel* _tmp5_ = NULL;
	GtkLabel* _tmp6_;
	GtkLabel* l;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (artist != NULL, NULL);
	_tmp0_ = (GtkViewport*) gtk_viewport_new (NULL, NULL);
	rv = g_object_ref_sink (_tmp0_);
	_tmp1_ = last_fm_artist_info_get_name (artist);
	_tmp2_ = g_strconcat (_tmp1_, ",", NULL);
	_tmp3_ = last_fm_artist_info_get_url (artist);
	_tmp4_ = g_strconcat (_tmp2_, _tmp3_, NULL);
	_tmp5_ = (GtkLabel*) gtk_label_new (_tmp4_);
	l = (_tmp6_ = g_object_ref_sink (_tmp5_), _g_free0 (_tmp4_), _g_free0 (_tmp2_), _tmp6_);
	gtk_container_add ((GtkContainer*) rv, (GtkWidget*) l);
	result = rv;
	_g_object_unref0 (l);
	return result;
}


GtkViewport* beat_box_song_editor_generate_album_page (BeatBoxSongEditor* self, LastFMAlbumInfo* album) {
	GtkViewport* result = NULL;
	GtkViewport* _tmp0_ = NULL;
	GtkViewport* rv;
	const gchar* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* l;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (album != NULL, NULL);
	_tmp0_ = (GtkViewport*) gtk_viewport_new (NULL, NULL);
	rv = g_object_ref_sink (_tmp0_);
	_tmp1_ = last_fm_album_info_get_name (album);
	_tmp2_ = (GtkLabel*) gtk_label_new (_tmp1_);
	l = g_object_ref_sink (_tmp2_);
	gtk_container_add ((GtkContainer*) rv, (GtkWidget*) l);
	result = rv;
	_g_object_unref0 (l);
	return result;
}


static void beat_box_song_editor_real_saveClicked (BeatBoxSongEditor* self) {
	g_return_if_fail (self != NULL);
	{
		GeeLinkedList* _tmp0_;
		GeeLinkedList* _s_list;
		gint _tmp1_;
		gint _s_size;
		gint _s_index;
		_tmp0_ = _g_object_ref0 (self->priv->_songs);
		_s_list = _tmp0_;
		_tmp1_ = gee_collection_get_size ((GeeCollection*) _s_list);
		_s_size = _tmp1_;
		_s_index = -1;
		while (TRUE) {
			gpointer _tmp2_ = NULL;
			BeatBoxSong* s;
			gpointer _tmp3_ = NULL;
			BeatBoxFieldEditor* _tmp4_;
			gboolean _tmp5_;
			gboolean _tmp6_;
			gpointer _tmp11_ = NULL;
			BeatBoxFieldEditor* _tmp12_;
			gboolean _tmp13_;
			gboolean _tmp14_;
			gpointer _tmp19_ = NULL;
			BeatBoxFieldEditor* _tmp20_;
			gboolean _tmp21_;
			gboolean _tmp22_;
			gpointer _tmp27_ = NULL;
			BeatBoxFieldEditor* _tmp28_;
			gboolean _tmp29_;
			gboolean _tmp30_;
			gpointer _tmp35_ = NULL;
			BeatBoxFieldEditor* _tmp36_;
			gboolean _tmp37_;
			gboolean _tmp38_;
			gpointer _tmp43_ = NULL;
			BeatBoxFieldEditor* _tmp44_;
			gboolean _tmp45_;
			gboolean _tmp46_;
			gpointer _tmp52_ = NULL;
			BeatBoxFieldEditor* _tmp53_;
			gboolean _tmp54_;
			gboolean _tmp55_;
			_s_index = _s_index + 1;
			if (!(_s_index < _s_size)) {
				break;
			}
			_tmp2_ = gee_abstract_list_get ((GeeAbstractList*) _s_list, _s_index);
			s = (BeatBoxSong*) _tmp2_;
			_tmp3_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Title");
			_tmp4_ = (BeatBoxFieldEditor*) _tmp3_;
			_tmp5_ = beat_box_field_editor_checked (_tmp4_);
			if ((_tmp6_ = _tmp5_, _g_object_unref0 (_tmp4_), _tmp6_)) {
				gpointer _tmp7_ = NULL;
				BeatBoxFieldEditor* _tmp8_;
				gchar* _tmp9_ = NULL;
				gchar* _tmp10_;
				_tmp7_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Title");
				_tmp8_ = (BeatBoxFieldEditor*) _tmp7_;
				_tmp9_ = beat_box_field_editor_get_value (_tmp8_);
				_tmp10_ = _tmp9_;
				beat_box_song_set_title (s, _tmp10_);
				_g_free0 (_tmp10_);
				_g_object_unref0 (_tmp8_);
			}
			_tmp11_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Artist");
			_tmp12_ = (BeatBoxFieldEditor*) _tmp11_;
			_tmp13_ = beat_box_field_editor_checked (_tmp12_);
			if ((_tmp14_ = _tmp13_, _g_object_unref0 (_tmp12_), _tmp14_)) {
				gpointer _tmp15_ = NULL;
				BeatBoxFieldEditor* _tmp16_;
				gchar* _tmp17_ = NULL;
				gchar* _tmp18_;
				_tmp15_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Artist");
				_tmp16_ = (BeatBoxFieldEditor*) _tmp15_;
				_tmp17_ = beat_box_field_editor_get_value (_tmp16_);
				_tmp18_ = _tmp17_;
				beat_box_song_set_artist (s, _tmp18_);
				_g_free0 (_tmp18_);
				_g_object_unref0 (_tmp16_);
			}
			_tmp19_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Album");
			_tmp20_ = (BeatBoxFieldEditor*) _tmp19_;
			_tmp21_ = beat_box_field_editor_checked (_tmp20_);
			if ((_tmp22_ = _tmp21_, _g_object_unref0 (_tmp20_), _tmp22_)) {
				gpointer _tmp23_ = NULL;
				BeatBoxFieldEditor* _tmp24_;
				gchar* _tmp25_ = NULL;
				gchar* _tmp26_;
				_tmp23_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Album");
				_tmp24_ = (BeatBoxFieldEditor*) _tmp23_;
				_tmp25_ = beat_box_field_editor_get_value (_tmp24_);
				_tmp26_ = _tmp25_;
				beat_box_song_set_album (s, _tmp26_);
				_g_free0 (_tmp26_);
				_g_object_unref0 (_tmp24_);
			}
			_tmp27_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Genre");
			_tmp28_ = (BeatBoxFieldEditor*) _tmp27_;
			_tmp29_ = beat_box_field_editor_checked (_tmp28_);
			if ((_tmp30_ = _tmp29_, _g_object_unref0 (_tmp28_), _tmp30_)) {
				gpointer _tmp31_ = NULL;
				BeatBoxFieldEditor* _tmp32_;
				gchar* _tmp33_ = NULL;
				gchar* _tmp34_;
				_tmp31_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Genre");
				_tmp32_ = (BeatBoxFieldEditor*) _tmp31_;
				_tmp33_ = beat_box_field_editor_get_value (_tmp32_);
				_tmp34_ = _tmp33_;
				beat_box_song_set_genre (s, _tmp34_);
				_g_free0 (_tmp34_);
				_g_object_unref0 (_tmp32_);
			}
			_tmp35_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Comment");
			_tmp36_ = (BeatBoxFieldEditor*) _tmp35_;
			_tmp37_ = beat_box_field_editor_checked (_tmp36_);
			if ((_tmp38_ = _tmp37_, _g_object_unref0 (_tmp36_), _tmp38_)) {
				gpointer _tmp39_ = NULL;
				BeatBoxFieldEditor* _tmp40_;
				gchar* _tmp41_ = NULL;
				gchar* _tmp42_;
				_tmp39_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Comment");
				_tmp40_ = (BeatBoxFieldEditor*) _tmp39_;
				_tmp41_ = beat_box_field_editor_get_value (_tmp40_);
				_tmp42_ = _tmp41_;
				beat_box_song_set_comment (s, _tmp42_);
				_g_free0 (_tmp42_);
				_g_object_unref0 (_tmp40_);
			}
			_tmp43_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Track");
			_tmp44_ = (BeatBoxFieldEditor*) _tmp43_;
			_tmp45_ = beat_box_field_editor_checked (_tmp44_);
			if ((_tmp46_ = _tmp45_, _g_object_unref0 (_tmp44_), _tmp46_)) {
				gpointer _tmp47_ = NULL;
				BeatBoxFieldEditor* _tmp48_;
				gchar* _tmp49_ = NULL;
				gchar* _tmp50_;
				gint _tmp51_;
				_tmp47_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Track");
				_tmp48_ = (BeatBoxFieldEditor*) _tmp47_;
				_tmp49_ = beat_box_field_editor_get_value (_tmp48_);
				_tmp50_ = _tmp49_;
				_tmp51_ = atoi (_tmp50_);
				beat_box_song_set_track (s, _tmp51_);
				_g_free0 (_tmp50_);
				_g_object_unref0 (_tmp48_);
			}
			_tmp52_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Year");
			_tmp53_ = (BeatBoxFieldEditor*) _tmp52_;
			_tmp54_ = beat_box_field_editor_checked (_tmp53_);
			if ((_tmp55_ = _tmp54_, _g_object_unref0 (_tmp53_), _tmp55_)) {
				gpointer _tmp56_ = NULL;
				BeatBoxFieldEditor* _tmp57_;
				gchar* _tmp58_ = NULL;
				gchar* _tmp59_;
				gint _tmp60_;
				_tmp56_ = gee_abstract_map_get ((GeeAbstractMap*) self->priv->fields, "Year");
				_tmp57_ = (BeatBoxFieldEditor*) _tmp56_;
				_tmp58_ = beat_box_field_editor_get_value (_tmp57_);
				_tmp59_ = _tmp58_;
				_tmp60_ = atoi (_tmp59_);
				beat_box_song_set_year (s, _tmp60_);
				_g_free0 (_tmp59_);
				_g_object_unref0 (_tmp57_);
			}
			_g_object_unref0 (s);
		}
		_g_object_unref0 (_s_list);
	}
	g_signal_emit_by_name (self, "songs-saved", self->priv->_songs);
	gtk_object_destroy ((GtkObject*) self);
}


void beat_box_song_editor_saveClicked (BeatBoxSongEditor* self) {
	BEAT_BOX_SONG_EDITOR_GET_CLASS (self)->saveClicked (self);
}


static void beat_box_song_editor_class_init (BeatBoxSongEditorClass * klass) {
	beat_box_song_editor_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (BeatBoxSongEditorPrivate));
	BEAT_BOX_SONG_EDITOR_CLASS (klass)->saveClicked = beat_box_song_editor_real_saveClicked;
	G_OBJECT_CLASS (klass)->finalize = beat_box_song_editor_finalize;
	g_signal_new ("songs_saved", BEAT_BOX_TYPE_SONG_EDITOR, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, GEE_TYPE_LINKED_LIST);
}


static void beat_box_song_editor_instance_init (BeatBoxSongEditor * self) {
	self->priv = BEAT_BOX_SONG_EDITOR_GET_PRIVATE (self);
}


static void beat_box_song_editor_finalize (GObject* obj) {
	BeatBoxSongEditor * self;
	self = BEAT_BOX_SONG_EDITOR (obj);
	_g_object_unref0 (self->priv->_songs);
	_g_object_unref0 (self->priv->content);
	_g_object_unref0 (self->priv->padding);
	_g_object_unref0 (self->priv->notebook);
	_g_object_unref0 (self->priv->editView);
	_g_object_unref0 (self->priv->vert);
	_g_object_unref0 (self->priv->horiz);
	_g_object_unref0 (self->priv->textVert);
	_g_object_unref0 (self->priv->numerVert);
	_g_object_unref0 (self->priv->fields);
	_g_object_unref0 (self->priv->_save);
	G_OBJECT_CLASS (beat_box_song_editor_parent_class)->finalize (obj);
}


GType beat_box_song_editor_get_type (void) {
	static volatile gsize beat_box_song_editor_type_id__volatile = 0;
	if (g_once_init_enter (&beat_box_song_editor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BeatBoxSongEditorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) beat_box_song_editor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BeatBoxSongEditor), 0, (GInstanceInitFunc) beat_box_song_editor_instance_init, NULL };
		GType beat_box_song_editor_type_id;
		beat_box_song_editor_type_id = g_type_register_static (GTK_TYPE_WINDOW, "BeatBoxSongEditor", &g_define_type_info, 0);
		g_once_init_leave (&beat_box_song_editor_type_id__volatile, beat_box_song_editor_type_id);
	}
	return beat_box_song_editor_type_id__volatile;
}


static void _beat_box_field_editor_entryChanged_gtk_editable_changed (GtkEditable* _sender, gpointer self) {
	beat_box_field_editor_entryChanged (self);
}


static void _beat_box_field_editor_textViewChanged_gtk_text_buffer_changed (GtkTextBuffer* _sender, gpointer self) {
	beat_box_field_editor_textViewChanged (self);
}


static gdouble double_parse (const gchar* str) {
	gdouble result = 0.0;
	gdouble _tmp0_;
	g_return_val_if_fail (str != NULL, 0.0);
	_tmp0_ = g_ascii_strtod (str, NULL);
	result = _tmp0_;
	return result;
}


static void _beat_box_field_editor_spinButtonChanged_gtk_adjustment_value_changed (GtkAdjustment* _sender, gpointer self) {
	beat_box_field_editor_spinButtonChanged (self);
}


static void _beat_box_field_editor_resetClicked_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	beat_box_field_editor_resetClicked (self);
}


BeatBoxFieldEditor* beat_box_field_editor_construct (GType object_type, const gchar* name, const gchar* original, GtkWidget* w) {
	BeatBoxFieldEditor * self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	GtkCheckButton* _tmp4_ = NULL;
	GtkCheckButton* _tmp5_;
	GtkLabel* _tmp6_ = NULL;
	GtkLabel* _tmp7_;
	gboolean _tmp8_ = FALSE;
	GtkButton* _tmp22_ = NULL;
	GtkButton* _tmp23_;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (original != NULL, NULL);
	g_return_val_if_fail (w != NULL, NULL);
	self = (BeatBoxFieldEditor*) g_object_new (object_type, NULL);
	_tmp0_ = g_strdup (name);
	_tmp1_ = _tmp0_;
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
	_tmp2_ = g_strdup (original);
	_tmp3_ = _tmp2_;
	_g_free0 (self->priv->_original);
	self->priv->_original = _tmp3_;
	gtk_box_set_spacing ((GtkBox*) self, 5);
	_tmp4_ = (GtkCheckButton*) gtk_check_button_new ();
	_tmp5_ = g_object_ref_sink (_tmp4_);
	_g_object_unref0 (self->priv->check);
	self->priv->check = _tmp5_;
	_tmp6_ = (GtkLabel*) gtk_label_new (self->priv->_name);
	_tmp7_ = g_object_ref_sink (_tmp6_);
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp7_;
	gtk_widget_set_size_request ((GtkWidget*) self->priv->label, 40, -1);
	gtk_label_set_justify (self->priv->label, GTK_JUSTIFY_LEFT);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) self->priv->check, FALSE, FALSE, (guint) 0);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) self->priv->label, FALSE, FALSE, (guint) 0);
	if (GTK_IS_ENTRY (w)) {
		_tmp8_ = !GTK_IS_SPIN_BUTTON (w);
	} else {
		_tmp8_ = FALSE;
	}
	if (_tmp8_) {
		GtkEntry* _tmp9_;
		GtkEntry* _tmp10_;
		gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->check, g_strcmp0 (original, "") != 0);
		_tmp9_ = _g_object_ref0 (GTK_ENTRY (w));
		_tmp10_ = _tmp9_;
		_g_object_unref0 (self->priv->entry);
		self->priv->entry = _tmp10_;
		gtk_widget_set_size_request ((GtkWidget*) self->priv->entry, 200, -1);
		gtk_entry_set_text (self->priv->entry, original);
		g_signal_connect_object ((GtkEditable*) self->priv->entry, "changed", (GCallback) _beat_box_field_editor_entryChanged_gtk_editable_changed, self, 0);
		gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) self->priv->entry, TRUE, TRUE, (guint) 0);
	} else {
		if (GTK_IS_TEXT_VIEW (w)) {
			GtkTextView* _tmp11_;
			GtkTextView* _tmp12_;
			GtkTextBuffer* _tmp13_ = NULL;
			GtkScrolledWindow* _tmp14_ = NULL;
			GtkScrolledWindow* scroll;
			GtkTextBuffer* _tmp15_ = NULL;
			gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->check, g_strcmp0 (original, "") != 0);
			_tmp11_ = _g_object_ref0 (GTK_TEXT_VIEW (w));
			_tmp12_ = _tmp11_;
			_g_object_unref0 (self->priv->textView);
			self->priv->textView = _tmp12_;
			gtk_widget_set_size_request ((GtkWidget*) self->priv->textView, 200, 100);
			gtk_text_view_set_wrap_mode (self->priv->textView, GTK_WRAP_WORD);
			_tmp13_ = gtk_text_view_get_buffer (self->priv->textView);
			g_object_set (_tmp13_, "text", original, NULL);
			_tmp14_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
			scroll = g_object_ref_sink (_tmp14_);
			gtk_scrolled_window_set_policy (scroll, GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
			gtk_container_add ((GtkContainer*) scroll, (GtkWidget*) self->priv->textView);
			_tmp15_ = gtk_text_view_get_buffer (self->priv->textView);
			g_signal_connect_object (_tmp15_, "changed", (GCallback) _beat_box_field_editor_textViewChanged_gtk_text_buffer_changed, self, 0);
			gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) scroll, TRUE, TRUE, (guint) 0);
			_g_object_unref0 (scroll);
		} else {
			if (GTK_IS_SPIN_BUTTON (w)) {
				GtkSpinButton* _tmp16_;
				GtkSpinButton* _tmp17_;
				gdouble _tmp18_;
				GtkAdjustment* _tmp19_ = NULL;
				gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->check, g_strcmp0 (original, "-1") != 0);
				_tmp16_ = _g_object_ref0 (GTK_SPIN_BUTTON (w));
				_tmp17_ = _tmp16_;
				_g_object_unref0 (self->priv->spinButton);
				self->priv->spinButton = _tmp17_;
				gtk_widget_set_size_request ((GtkWidget*) self->priv->spinButton, 80, -1);
				_tmp18_ = double_parse (original);
				gtk_spin_button_set_value (self->priv->spinButton, _tmp18_);
				_tmp19_ = gtk_spin_button_get_adjustment (self->priv->spinButton);
				g_signal_connect_object (_tmp19_, "value-changed", (GCallback) _beat_box_field_editor_spinButtonChanged_gtk_adjustment_value_changed, self, 0);
				gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) self->priv->spinButton, TRUE, TRUE, (guint) 0);
			} else {
				if (GTK_IS_IMAGE (w)) {
					GtkImage* _tmp20_;
					GtkImage* _tmp21_;
					gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->check, g_strcmp0 (original, "") != 0);
					_tmp20_ = _g_object_ref0 (GTK_IMAGE (w));
					_tmp21_ = _tmp20_;
					_g_object_unref0 (self->priv->image);
					self->priv->image = _tmp21_;
					gtk_widget_set_size_request ((GtkWidget*) self->priv->image, 100, 100);
					gtk_image_set_from_file (self->priv->image, original);
					gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) self->priv->image, TRUE, TRUE, (guint) 0);
				}
			}
		}
	}
	_tmp22_ = (GtkButton*) gtk_button_new_from_stock (GTK_STOCK_CLEAR);
	_tmp23_ = g_object_ref_sink (_tmp22_);
	_g_object_unref0 (self->priv->reset);
	self->priv->reset = _tmp23_;
	g_signal_connect_object (self->priv->reset, "clicked", (GCallback) _beat_box_field_editor_resetClicked_gtk_button_clicked, self, 0);
	gtk_box_pack_end ((GtkBox*) self, (GtkWidget*) self->priv->reset, FALSE, FALSE, (guint) 0);
	return self;
}


BeatBoxFieldEditor* beat_box_field_editor_new (const gchar* name, const gchar* original, GtkWidget* w) {
	return beat_box_field_editor_construct (BEAT_BOX_TYPE_FIELD_EDITOR, name, original, w);
}


void beat_box_field_editor_set_check_visible (BeatBoxFieldEditor* self, gboolean val) {
	g_return_if_fail (self != NULL);
	gtk_widget_set_visible ((GtkWidget*) self->priv->check, FALSE);
}


static void beat_box_field_editor_real_entryChanged (BeatBoxFieldEditor* self) {
	const gchar* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_entry_get_text (self->priv->entry);
	if (g_strcmp0 (_tmp0_, self->priv->_original) != 0) {
		gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->check, TRUE);
	} else {
		gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->check, FALSE);
	}
}


void beat_box_field_editor_entryChanged (BeatBoxFieldEditor* self) {
	BEAT_BOX_FIELD_EDITOR_GET_CLASS (self)->entryChanged (self);
}


static void beat_box_field_editor_real_textViewChanged (BeatBoxFieldEditor* self) {
	GtkTextBuffer* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	gboolean _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_text_view_get_buffer (self->priv->textView);
	_tmp2_ = (g_object_get (_tmp0_, "text", &_tmp1_, NULL), _tmp1_);
	if ((_tmp3_ = g_strcmp0 (_tmp2_, self->priv->_original) != 0, _g_free0 (_tmp2_), _tmp3_)) {
		gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->check, TRUE);
	} else {
		gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->check, FALSE);
	}
}


void beat_box_field_editor_textViewChanged (BeatBoxFieldEditor* self) {
	BEAT_BOX_FIELD_EDITOR_GET_CLASS (self)->textViewChanged (self);
}


static void beat_box_field_editor_real_spinButtonChanged (BeatBoxFieldEditor* self) {
	gdouble _tmp0_;
	gdouble _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_spin_button_get_value (self->priv->spinButton);
	_tmp1_ = double_parse (self->priv->_original);
	if (_tmp0_ != _tmp1_) {
		gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->check, TRUE);
	} else {
		gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->check, FALSE);
	}
}


void beat_box_field_editor_spinButtonChanged (BeatBoxFieldEditor* self) {
	BEAT_BOX_FIELD_EDITOR_GET_CLASS (self)->spinButtonChanged (self);
}


gboolean beat_box_field_editor_checked (BeatBoxFieldEditor* self) {
	gboolean result = FALSE;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->check);
	result = _tmp0_;
	return result;
}


static void beat_box_field_editor_real_resetClicked (BeatBoxFieldEditor* self) {
	g_return_if_fail (self != NULL);
	if (self->priv->entry != NULL) {
		gtk_entry_set_text (self->priv->entry, self->priv->_original);
	} else {
		if (self->priv->textView != NULL) {
			GtkTextBuffer* _tmp0_ = NULL;
			_tmp0_ = gtk_text_view_get_buffer (self->priv->textView);
			g_object_set (_tmp0_, "text", self->priv->_original, NULL);
		} else {
			if (self->priv->spinButton != NULL) {
				gdouble _tmp1_;
				_tmp1_ = double_parse (self->priv->_original);
				gtk_spin_button_set_value (self->priv->spinButton, _tmp1_);
			} else {
				if (self->priv->image != NULL) {
					gtk_image_set_from_file (self->priv->image, self->priv->_original);
				}
			}
		}
	}
}


void beat_box_field_editor_resetClicked (BeatBoxFieldEditor* self) {
	BEAT_BOX_FIELD_EDITOR_GET_CLASS (self)->resetClicked (self);
}


static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	gchar* _tmp4_;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	result = (_tmp4_ = _tmp3_, _tmp1_ = (g_free (_tmp1_), NULL), _tmp4_);
	return result;
}


gchar* beat_box_field_editor_get_value (BeatBoxFieldEditor* self) {
	gchar* result = NULL;
	gchar* _tmp7_;
	g_return_val_if_fail (self != NULL, NULL);
	if (self->priv->entry != NULL) {
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_;
		_tmp0_ = gtk_entry_get_text (self->priv->entry);
		_tmp1_ = g_strdup (_tmp0_);
		result = _tmp1_;
		return result;
	} else {
		if (self->priv->textView != NULL) {
			GtkTextBuffer* _tmp2_ = NULL;
			gchar* _tmp3_ = NULL;
			_tmp2_ = gtk_text_view_get_buffer (self->priv->textView);
			result = (g_object_get (_tmp2_, "text", &_tmp3_, NULL), _tmp3_);
			return result;
		} else {
			if (self->priv->spinButton != NULL) {
				gdouble _tmp4_;
				gchar* _tmp5_ = NULL;
				_tmp4_ = gtk_spin_button_get_value (self->priv->spinButton);
				_tmp5_ = double_to_string (_tmp4_);
				result = _tmp5_;
				return result;
			} else {
				if (self->priv->image != NULL) {
					gchar* _tmp6_ = NULL;
					result = (g_object_get (self->priv->image, "file", &_tmp6_, NULL), _tmp6_);
					return result;
				}
			}
		}
	}
	_tmp7_ = g_strdup ("");
	result = _tmp7_;
	return result;
}


static void beat_box_field_editor_class_init (BeatBoxFieldEditorClass * klass) {
	beat_box_field_editor_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (BeatBoxFieldEditorPrivate));
	BEAT_BOX_FIELD_EDITOR_CLASS (klass)->entryChanged = beat_box_field_editor_real_entryChanged;
	BEAT_BOX_FIELD_EDITOR_CLASS (klass)->textViewChanged = beat_box_field_editor_real_textViewChanged;
	BEAT_BOX_FIELD_EDITOR_CLASS (klass)->spinButtonChanged = beat_box_field_editor_real_spinButtonChanged;
	BEAT_BOX_FIELD_EDITOR_CLASS (klass)->resetClicked = beat_box_field_editor_real_resetClicked;
	G_OBJECT_CLASS (klass)->finalize = beat_box_field_editor_finalize;
}


static void beat_box_field_editor_instance_init (BeatBoxFieldEditor * self) {
	self->priv = BEAT_BOX_FIELD_EDITOR_GET_PRIVATE (self);
}


static void beat_box_field_editor_finalize (GObject* obj) {
	BeatBoxFieldEditor * self;
	self = BEAT_BOX_FIELD_EDITOR (obj);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_original);
	_g_object_unref0 (self->priv->check);
	_g_object_unref0 (self->priv->label);
	_g_object_unref0 (self->priv->entry);
	_g_object_unref0 (self->priv->textView);
	_g_object_unref0 (self->priv->spinButton);
	_g_object_unref0 (self->priv->image);
	_g_object_unref0 (self->priv->reset);
	G_OBJECT_CLASS (beat_box_field_editor_parent_class)->finalize (obj);
}


GType beat_box_field_editor_get_type (void) {
	static volatile gsize beat_box_field_editor_type_id__volatile = 0;
	if (g_once_init_enter (&beat_box_field_editor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BeatBoxFieldEditorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) beat_box_field_editor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BeatBoxFieldEditor), 0, (GInstanceInitFunc) beat_box_field_editor_instance_init, NULL };
		GType beat_box_field_editor_type_id;
		beat_box_field_editor_type_id = g_type_register_static (GTK_TYPE_HBOX, "BeatBoxFieldEditor", &g_define_type_info, 0);
		g_once_init_leave (&beat_box_field_editor_type_id__volatile, beat_box_field_editor_type_id);
	}
	return beat_box_field_editor_type_id__volatile;
}



