.TH BEATBOX 1 "May 18, 2011"
.SH NAME
beatbox \- music player written in vala
.SH DESCRIPTION
.B BeatBox
is an easy to use, stable, fast and good looking music library organizer written in vala.

It has many modern features including Last.FM integration to download artwork, information, and scrobble your music, playlists and smart playlists, find music similar to the currently playing song, simple UI, fast searching for music, queue system, mass song editing and more...
commands.
.SH AUTHOR
beatbox was written by Scott Ringwelski <sgringwe@mtu.edu>.
.PP
This manual page was written by Devid Antonio Filoni <d.filoni@ubuntu.com>,
for the Debian project (and may be used by others).
