.TH "noise" "1" "June 2014" "" "Noise"
.
.SH "NAME"
\fBnoise\fR \- simple, fast and good-looking music player
.
.SH "SYNOPSIS"
\fBnoise\fR [\fIOPTION...\fR] [\fIURI...\fR]
.
.SH "DESCRIPTION"
\fBnoise\fR is an easy to use, stable, fast and good looking music library
organizer written in Vala and designed for elementary OS.
.
.P
It has many modern features including Last.FM integration to download artwork, information, and scrobble your music, playlists and smart playlists, find music similar to the currently playing song, simple UI, fast searching for music, queue system, mass song editing and more\.\.\.
.
.P
Unlike most music players, passing a file or URI while another track is playing will not cause the new track to be played immediately\. Instead the new track(s) will be enqueued and played after the currently played one finishes\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-display=\fR\fIDISPLAY\fR
X display to use\.
.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Enable debug logging\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options\.
.
.TP
\fB\-h\fR, \fB\-\-help\-gtk\fR
Show GTK\+ help options\.
.
.TP
\fB\-a\fR, \fB\-\-about\fR
Show a graphical About dialog\.
.
.SH "AUTHORS"
Victor Martinez \<victor@elementaryos\.org\>, Scott Ringwelski \<sgringwe@gmail\.com\>, Corentin Noël \<corentin@elementaryos\.org\>, Lucas Baudin \<xapantu@gmail\.com\> et al\.
