#! /usr/bin/env python
# WAF build script for Postler (based on Midori's wscript)
#
# This script is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# See the file COPYING for the full license text.

obj = bld.new_task_gen ('cc', 'program')
obj.name = 'beatbox'
obj.target = 'beatbox'
obj.includes = '. ..'
obj.find_sources_in_dirs ('.')
obj.uselib = 'GIO GTHREAD GTK LIBNOTIFY INDICATE UNIQUE WEBKIT'
obj.packages = 'gtk+-2.0 gee-1.0 gstreamer-0.10 taglib_c gio-2.0 sqlheavy-0.1 webkit-1.0 libxml-2.0 gconf-2.0 libnotify gnet-2.0 dbus-glib-1 unique-1.0'
obj.vapi_dirs = '.'

bld.add_subdirs('Objects LastFM Dialogs Widgets')

if bld.env['HAVE_INDICATE']:
    obj.packages += ' indicate'
