/* SimilarPane.c generated by valac 0.11.6, the Vala compiler
 * generated from SimilarPane.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define BEAT_BOX_TYPE_SIMILAR_PANE (beat_box_similar_pane_get_type ())
#define BEAT_BOX_SIMILAR_PANE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_SIMILAR_PANE, BeatBoxSimilarPane))
#define BEAT_BOX_SIMILAR_PANE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_SIMILAR_PANE, BeatBoxSimilarPaneClass))
#define BEAT_BOX_IS_SIMILAR_PANE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_SIMILAR_PANE))
#define BEAT_BOX_IS_SIMILAR_PANE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_SIMILAR_PANE))
#define BEAT_BOX_SIMILAR_PANE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_SIMILAR_PANE, BeatBoxSimilarPaneClass))

typedef struct _BeatBoxSimilarPane BeatBoxSimilarPane;
typedef struct _BeatBoxSimilarPaneClass BeatBoxSimilarPaneClass;
typedef struct _BeatBoxSimilarPanePrivate BeatBoxSimilarPanePrivate;

#define BEAT_BOX_TYPE_SONG (beat_box_song_get_type ())
#define BEAT_BOX_SONG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_SONG, BeatBoxSong))
#define BEAT_BOX_SONG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_SONG, BeatBoxSongClass))
#define BEAT_BOX_IS_SONG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_SONG))
#define BEAT_BOX_IS_SONG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_SONG))
#define BEAT_BOX_SONG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_SONG, BeatBoxSongClass))

typedef struct _BeatBoxSong BeatBoxSong;
typedef struct _BeatBoxSongClass BeatBoxSongClass;

#define BEAT_BOX_TYPE_LIBRARY_MANAGER (beat_box_library_manager_get_type ())
#define BEAT_BOX_LIBRARY_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_LIBRARY_MANAGER, BeatBoxLibraryManager))
#define BEAT_BOX_LIBRARY_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_LIBRARY_MANAGER, BeatBoxLibraryManagerClass))
#define BEAT_BOX_IS_LIBRARY_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_LIBRARY_MANAGER))
#define BEAT_BOX_IS_LIBRARY_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_LIBRARY_MANAGER))
#define BEAT_BOX_LIBRARY_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_LIBRARY_MANAGER, BeatBoxLibraryManagerClass))

typedef struct _BeatBoxLibraryManager BeatBoxLibraryManager;
typedef struct _BeatBoxLibraryManagerClass BeatBoxLibraryManagerClass;

#define BEAT_BOX_TYPE_LIBRARY_WINDOW (beat_box_library_window_get_type ())
#define BEAT_BOX_LIBRARY_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_LIBRARY_WINDOW, BeatBoxLibraryWindow))
#define BEAT_BOX_LIBRARY_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_LIBRARY_WINDOW, BeatBoxLibraryWindowClass))
#define BEAT_BOX_IS_LIBRARY_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_LIBRARY_WINDOW))
#define BEAT_BOX_IS_LIBRARY_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_LIBRARY_WINDOW))
#define BEAT_BOX_LIBRARY_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_LIBRARY_WINDOW, BeatBoxLibraryWindowClass))

typedef struct _BeatBoxLibraryWindow BeatBoxLibraryWindow;
typedef struct _BeatBoxLibraryWindowClass BeatBoxLibraryWindowClass;

#define BEAT_BOX_TYPE_MUSIC_TREE_VIEW (beat_box_music_tree_view_get_type ())
#define BEAT_BOX_MUSIC_TREE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_MUSIC_TREE_VIEW, BeatBoxMusicTreeView))
#define BEAT_BOX_MUSIC_TREE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_MUSIC_TREE_VIEW, BeatBoxMusicTreeViewClass))
#define BEAT_BOX_IS_MUSIC_TREE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_MUSIC_TREE_VIEW))
#define BEAT_BOX_IS_MUSIC_TREE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_MUSIC_TREE_VIEW))
#define BEAT_BOX_MUSIC_TREE_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_MUSIC_TREE_VIEW, BeatBoxMusicTreeViewClass))

typedef struct _BeatBoxMusicTreeView BeatBoxMusicTreeView;
typedef struct _BeatBoxMusicTreeViewClass BeatBoxMusicTreeViewClass;

#define BEAT_BOX_TYPE_SIMILAR_SONGS_VIEW (beat_box_similar_songs_view_get_type ())
#define BEAT_BOX_SIMILAR_SONGS_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_SIMILAR_SONGS_VIEW, BeatBoxSimilarSongsView))
#define BEAT_BOX_SIMILAR_SONGS_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_SIMILAR_SONGS_VIEW, BeatBoxSimilarSongsViewClass))
#define BEAT_BOX_IS_SIMILAR_SONGS_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_SIMILAR_SONGS_VIEW))
#define BEAT_BOX_IS_SIMILAR_SONGS_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_SIMILAR_SONGS_VIEW))
#define BEAT_BOX_SIMILAR_SONGS_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_SIMILAR_SONGS_VIEW, BeatBoxSimilarSongsViewClass))

typedef struct _BeatBoxSimilarSongsView BeatBoxSimilarSongsView;
typedef struct _BeatBoxSimilarSongsViewClass BeatBoxSimilarSongsViewClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _BeatBoxLibraryManagerPrivate BeatBoxLibraryManagerPrivate;

#define BEAT_BOX_TYPE_SETTINGS (beat_box_settings_get_type ())
#define BEAT_BOX_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_SETTINGS, BeatBoxSettings))
#define BEAT_BOX_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_SETTINGS, BeatBoxSettingsClass))
#define BEAT_BOX_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_SETTINGS))
#define BEAT_BOX_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_SETTINGS))
#define BEAT_BOX_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_SETTINGS, BeatBoxSettingsClass))

typedef struct _BeatBoxSettings BeatBoxSettings;
typedef struct _BeatBoxSettingsClass BeatBoxSettingsClass;

#define BEAT_BOX_TYPE_DATA_BASE_MANAGER (beat_box_data_base_manager_get_type ())
#define BEAT_BOX_DATA_BASE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_DATA_BASE_MANAGER, BeatBoxDataBaseManager))
#define BEAT_BOX_DATA_BASE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_DATA_BASE_MANAGER, BeatBoxDataBaseManagerClass))
#define BEAT_BOX_IS_DATA_BASE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_DATA_BASE_MANAGER))
#define BEAT_BOX_IS_DATA_BASE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_DATA_BASE_MANAGER))
#define BEAT_BOX_DATA_BASE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_DATA_BASE_MANAGER, BeatBoxDataBaseManagerClass))

typedef struct _BeatBoxDataBaseManager BeatBoxDataBaseManager;
typedef struct _BeatBoxDataBaseManagerClass BeatBoxDataBaseManagerClass;

#define BEAT_BOX_TYPE_FILE_OPERATOR (beat_box_file_operator_get_type ())
#define BEAT_BOX_FILE_OPERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_FILE_OPERATOR, BeatBoxFileOperator))
#define BEAT_BOX_FILE_OPERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_FILE_OPERATOR, BeatBoxFileOperatorClass))
#define BEAT_BOX_IS_FILE_OPERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_FILE_OPERATOR))
#define BEAT_BOX_IS_FILE_OPERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_FILE_OPERATOR))
#define BEAT_BOX_FILE_OPERATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_FILE_OPERATOR, BeatBoxFileOperatorClass))

typedef struct _BeatBoxFileOperator BeatBoxFileOperator;
typedef struct _BeatBoxFileOperatorClass BeatBoxFileOperatorClass;

#define BEAT_BOX_TYPE_STREAM_PLAYER (beat_box_stream_player_get_type ())
#define BEAT_BOX_STREAM_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_STREAM_PLAYER, BeatBoxStreamPlayer))
#define BEAT_BOX_STREAM_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_STREAM_PLAYER, BeatBoxStreamPlayerClass))
#define BEAT_BOX_IS_STREAM_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_STREAM_PLAYER))
#define BEAT_BOX_IS_STREAM_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_STREAM_PLAYER))
#define BEAT_BOX_STREAM_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_STREAM_PLAYER, BeatBoxStreamPlayerClass))

typedef struct _BeatBoxStreamPlayer BeatBoxStreamPlayer;
typedef struct _BeatBoxStreamPlayerClass BeatBoxStreamPlayerClass;

#define LAST_FM_TYPE_CORE (last_fm_core_get_type ())
#define LAST_FM_CORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAST_FM_TYPE_CORE, LastFMCore))
#define LAST_FM_CORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAST_FM_TYPE_CORE, LastFMCoreClass))
#define LAST_FM_IS_CORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAST_FM_TYPE_CORE))
#define LAST_FM_IS_CORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAST_FM_TYPE_CORE))
#define LAST_FM_CORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAST_FM_TYPE_CORE, LastFMCoreClass))

typedef struct _LastFMCore LastFMCore;
typedef struct _LastFMCoreClass LastFMCoreClass;

#define BEAT_BOX_TYPE_SONG_INFO (beat_box_song_info_get_type ())
#define BEAT_BOX_SONG_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_SONG_INFO, BeatBoxSongInfo))
#define BEAT_BOX_SONG_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_SONG_INFO, BeatBoxSongInfoClass))
#define BEAT_BOX_IS_SONG_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_SONG_INFO))
#define BEAT_BOX_IS_SONG_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_SONG_INFO))
#define BEAT_BOX_SONG_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_SONG_INFO, BeatBoxSongInfoClass))

typedef struct _BeatBoxSongInfo BeatBoxSongInfo;
typedef struct _BeatBoxSongInfoClass BeatBoxSongInfoClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _BeatBoxSongInfoPrivate BeatBoxSongInfoPrivate;

#define LAST_FM_TYPE_ARTIST_INFO (last_fm_artist_info_get_type ())
#define LAST_FM_ARTIST_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAST_FM_TYPE_ARTIST_INFO, LastFMArtistInfo))
#define LAST_FM_ARTIST_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAST_FM_TYPE_ARTIST_INFO, LastFMArtistInfoClass))
#define LAST_FM_IS_ARTIST_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAST_FM_TYPE_ARTIST_INFO))
#define LAST_FM_IS_ARTIST_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAST_FM_TYPE_ARTIST_INFO))
#define LAST_FM_ARTIST_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAST_FM_TYPE_ARTIST_INFO, LastFMArtistInfoClass))

typedef struct _LastFMArtistInfo LastFMArtistInfo;
typedef struct _LastFMArtistInfoClass LastFMArtistInfoClass;

#define LAST_FM_TYPE_TRACK_INFO (last_fm_track_info_get_type ())
#define LAST_FM_TRACK_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAST_FM_TYPE_TRACK_INFO, LastFMTrackInfo))
#define LAST_FM_TRACK_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAST_FM_TYPE_TRACK_INFO, LastFMTrackInfoClass))
#define LAST_FM_IS_TRACK_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAST_FM_TYPE_TRACK_INFO))
#define LAST_FM_IS_TRACK_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAST_FM_TYPE_TRACK_INFO))
#define LAST_FM_TRACK_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAST_FM_TYPE_TRACK_INFO, LastFMTrackInfoClass))

typedef struct _LastFMTrackInfo LastFMTrackInfo;
typedef struct _LastFMTrackInfoClass LastFMTrackInfoClass;

#define LAST_FM_TYPE_ALBUM_INFO (last_fm_album_info_get_type ())
#define LAST_FM_ALBUM_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAST_FM_TYPE_ALBUM_INFO, LastFMAlbumInfo))
#define LAST_FM_ALBUM_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAST_FM_TYPE_ALBUM_INFO, LastFMAlbumInfoClass))
#define LAST_FM_IS_ALBUM_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAST_FM_TYPE_ALBUM_INFO))
#define LAST_FM_IS_ALBUM_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAST_FM_TYPE_ALBUM_INFO))
#define LAST_FM_ALBUM_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAST_FM_TYPE_ALBUM_INFO, LastFMAlbumInfoClass))

typedef struct _LastFMAlbumInfo LastFMAlbumInfo;
typedef struct _LastFMAlbumInfoClass LastFMAlbumInfoClass;

#define BEAT_BOX_TYPE_PLAYLIST (beat_box_playlist_get_type ())
#define BEAT_BOX_PLAYLIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BEAT_BOX_TYPE_PLAYLIST, BeatBoxPlaylist))
#define BEAT_BOX_PLAYLIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BEAT_BOX_TYPE_PLAYLIST, BeatBoxPlaylistClass))
#define BEAT_BOX_IS_PLAYLIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BEAT_BOX_TYPE_PLAYLIST))
#define BEAT_BOX_IS_PLAYLIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BEAT_BOX_TYPE_PLAYLIST))
#define BEAT_BOX_PLAYLIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BEAT_BOX_TYPE_PLAYLIST, BeatBoxPlaylistClass))

typedef struct _BeatBoxPlaylist BeatBoxPlaylist;
typedef struct _BeatBoxPlaylistClass BeatBoxPlaylistClass;

struct _BeatBoxSimilarPane {
	GtkHPaned parent_instance;
	BeatBoxSimilarPanePrivate * priv;
	BeatBoxSong* _base;
	GeeCollection* _have;
};

struct _BeatBoxSimilarPaneClass {
	GtkHPanedClass parent_class;
	void (*refreshClicked) (BeatBoxSimilarPane* self);
	void (*transferPlaybackClicked) (BeatBoxSimilarPane* self);
	void (*saveClicked) (BeatBoxSimilarPane* self);
	void (*paneHandleSet) (BeatBoxSimilarPane* self, GdkRectangle* rectangle);
};

struct _BeatBoxSimilarPanePrivate {
	BeatBoxLibraryManager* _lm;
	BeatBoxLibraryWindow* _lw;
	BeatBoxSong* _next;
	GeeCollection* _shouldHave;
	GtkVBox* left;
	GtkToolbar* toolbar;
	GtkToolButton* refresh;
	GtkLabel* toolInfo;
	GtkToolButton* transferPlayback;
	GtkToolButton* save;
	BeatBoxMusicTreeView* similars;
	BeatBoxSimilarSongsView* ssv;
};

struct _BeatBoxLibraryManager {
	GObject parent_instance;
	BeatBoxLibraryManagerPrivate * priv;
	BeatBoxSettings* settings;
	BeatBoxDataBaseManager* dbm;
	BeatBoxFileOperator* fo;
	BeatBoxStreamPlayer* player;
	LastFMCore* lfm;
	gint _played_index;
	gint _current_index;
	gint _current_shuffled_index;
	BeatBoxSongInfo* song_info;
	gboolean playing;
	gboolean repeat;
	gboolean shuffle;
	gboolean doing_file_operations;
};

struct _BeatBoxLibraryManagerClass {
	GObjectClass parent_class;
	void (*dbProgress) (BeatBoxLibraryManager* self, const gchar* message, gdouble progress);
};

struct _BeatBoxSongInfo {
	GObject parent_instance;
	BeatBoxSongInfoPrivate * priv;
	BeatBoxSong* song;
	LastFMArtistInfo* artist;
	LastFMTrackInfo* track;
	LastFMAlbumInfo* album;
};

struct _BeatBoxSongInfoClass {
	GObjectClass parent_class;
};


static gpointer beat_box_similar_pane_parent_class = NULL;

GType beat_box_similar_pane_get_type (void) G_GNUC_CONST;
GType beat_box_song_get_type (void) G_GNUC_CONST;
GType beat_box_library_manager_get_type (void) G_GNUC_CONST;
GType beat_box_library_window_get_type (void) G_GNUC_CONST;
GType beat_box_music_tree_view_get_type (void) G_GNUC_CONST;
GType beat_box_similar_songs_view_get_type (void) G_GNUC_CONST;
#define BEAT_BOX_SIMILAR_PANE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), BEAT_BOX_TYPE_SIMILAR_PANE, BeatBoxSimilarPanePrivate))
enum  {
	BEAT_BOX_SIMILAR_PANE_DUMMY_PROPERTY
};
BeatBoxSimilarPane* beat_box_similar_pane_new (BeatBoxLibraryManager* lm, BeatBoxLibraryWindow* lw);
BeatBoxSimilarPane* beat_box_similar_pane_construct (GType object_type, BeatBoxLibraryManager* lm, BeatBoxLibraryWindow* lw);
BeatBoxMusicTreeView* beat_box_music_tree_view_new (BeatBoxLibraryManager* lmm, BeatBoxLibraryWindow* lww, gint sort);
BeatBoxMusicTreeView* beat_box_music_tree_view_construct (GType object_type, BeatBoxLibraryManager* lmm, BeatBoxLibraryWindow* lww, gint sort);
BeatBoxSimilarSongsView* beat_box_similar_songs_view_new (BeatBoxLibraryManager* lm, BeatBoxLibraryWindow* lw);
BeatBoxSimilarSongsView* beat_box_similar_songs_view_construct (GType object_type, BeatBoxLibraryManager* lm, BeatBoxLibraryWindow* lw);
void beat_box_music_tree_view_set_hint (BeatBoxMusicTreeView* self, const gchar* the_hint);
GType beat_box_settings_get_type (void) G_GNUC_CONST;
GType beat_box_data_base_manager_get_type (void) G_GNUC_CONST;
GType beat_box_file_operator_get_type (void) G_GNUC_CONST;
GType beat_box_stream_player_get_type (void) G_GNUC_CONST;
GType last_fm_core_get_type (void) G_GNUC_CONST;
GType beat_box_song_info_get_type (void) G_GNUC_CONST;
gint beat_box_settings_getMoreWidth (BeatBoxSettings* self);
void beat_box_similar_pane_refreshClicked (BeatBoxSimilarPane* self);
static void _beat_box_similar_pane_refreshClicked_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self);
void beat_box_similar_pane_transferPlaybackClicked (BeatBoxSimilarPane* self);
static void _beat_box_similar_pane_transferPlaybackClicked_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self);
void beat_box_similar_pane_saveClicked (BeatBoxSimilarPane* self);
static void _beat_box_similar_pane_saveClicked_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self);
void beat_box_similar_pane_paneHandleSet (BeatBoxSimilarPane* self, GdkRectangle* rectangle);
static void _beat_box_similar_pane_paneHandleSet_gtk_widget_size_allocate (GtkWidget* _sender, GdkRectangle* allocation, gpointer self);
void beat_box_similar_pane_updateSongs (BeatBoxSimilarPane* self, BeatBoxSong* la, GeeCollection* have, GeeCollection* shouldHave);
GeeCollection* beat_box_library_manager_current_songs (BeatBoxLibraryManager* self);
GeeSet* beat_box_music_tree_view_get_songs (BeatBoxMusicTreeView* self);
void beat_box_similar_pane_updateDisplay (BeatBoxSimilarPane* self);
const gchar* beat_box_song_get_title (BeatBoxSong* self);
const gchar* beat_box_song_get_artist (BeatBoxSong* self);
void beat_box_music_tree_view_populateView (BeatBoxMusicTreeView* self, GeeCollection* songs, gboolean is_search);
void beat_box_similar_songs_view_populateView (BeatBoxSimilarSongsView* self, GeeCollection* nSongs);
GType last_fm_artist_info_get_type (void) G_GNUC_CONST;
GType last_fm_track_info_get_type (void) G_GNUC_CONST;
GType last_fm_album_info_get_type (void) G_GNUC_CONST;
gboolean beat_box_music_tree_view_updateSong (BeatBoxMusicTreeView* self, gint i);
gint beat_box_song_get_rowid (BeatBoxSong* self);
static void beat_box_similar_pane_real_refreshClicked (BeatBoxSimilarPane* self);
static void beat_box_similar_pane_real_transferPlaybackClicked (BeatBoxSimilarPane* self);
void beat_box_music_tree_view_setAsCurrentList (BeatBoxMusicTreeView* self, const gchar* current_song_path);
static void beat_box_similar_pane_real_saveClicked (BeatBoxSimilarPane* self);
BeatBoxPlaylist* beat_box_playlist_new (void);
BeatBoxPlaylist* beat_box_playlist_construct (GType object_type);
GType beat_box_playlist_get_type (void) G_GNUC_CONST;
void beat_box_playlist_set_name (BeatBoxPlaylist* self, const gchar* value);
void beat_box_playlist_addSong (BeatBoxPlaylist* self, BeatBoxSong* s);
BeatBoxSong* beat_box_library_manager_song_from_id (BeatBoxLibraryManager* self, gint id);
gint beat_box_library_manager_add_playlist (BeatBoxLibraryManager* self, BeatBoxPlaylist* p);
void beat_box_library_window_addSideListItem (BeatBoxLibraryWindow* self, GObject* o);
static void beat_box_similar_pane_real_paneHandleSet (BeatBoxSimilarPane* self, GdkRectangle* rectangle);
void beat_box_settings_setMoreWidth (BeatBoxSettings* self, gint val);
static void beat_box_similar_pane_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _beat_box_similar_pane_refreshClicked_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self) {
	beat_box_similar_pane_refreshClicked (self);
}


static void _beat_box_similar_pane_transferPlaybackClicked_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self) {
	beat_box_similar_pane_transferPlaybackClicked (self);
}


static void _beat_box_similar_pane_saveClicked_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self) {
	beat_box_similar_pane_saveClicked (self);
}


static void _beat_box_similar_pane_paneHandleSet_gtk_widget_size_allocate (GtkWidget* _sender, GdkRectangle* allocation, gpointer self) {
	beat_box_similar_pane_paneHandleSet (self, allocation);
}


BeatBoxSimilarPane* beat_box_similar_pane_construct (GType object_type, BeatBoxLibraryManager* lm, BeatBoxLibraryWindow* lw) {
	BeatBoxSimilarPane * self = NULL;
	BeatBoxLibraryManager* _tmp0_;
	BeatBoxLibraryManager* _tmp1_;
	BeatBoxLibraryWindow* _tmp2_;
	BeatBoxLibraryWindow* _tmp3_;
	GtkVBox* _tmp4_ = NULL;
	GtkVBox* _tmp5_;
	GtkToolbar* _tmp6_ = NULL;
	GtkToolbar* _tmp7_;
	GtkToolButton* _tmp8_ = NULL;
	GtkToolButton* _tmp9_;
	GtkToolButton* _tmp10_ = NULL;
	GtkToolButton* _tmp11_;
	GtkLabel* _tmp12_ = NULL;
	GtkLabel* _tmp13_;
	GtkToolButton* _tmp14_ = NULL;
	GtkToolButton* _tmp15_;
	BeatBoxMusicTreeView* _tmp16_ = NULL;
	BeatBoxMusicTreeView* _tmp17_;
	BeatBoxSimilarSongsView* _tmp18_ = NULL;
	BeatBoxSimilarSongsView* _tmp19_;
	GtkToolItem* _tmp20_ = NULL;
	GtkToolItem* toolInfoBin;
	gint _tmp21_;
	g_return_val_if_fail (lm != NULL, NULL);
	g_return_val_if_fail (lw != NULL, NULL);
	self = (BeatBoxSimilarPane*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (lm);
	_tmp1_ = _tmp0_;
	_g_object_unref0 (self->priv->_lm);
	self->priv->_lm = _tmp1_;
	_tmp2_ = _g_object_ref0 (lw);
	_tmp3_ = _tmp2_;
	_g_object_unref0 (self->priv->_lw);
	self->priv->_lw = _tmp3_;
	_tmp4_ = (GtkVBox*) gtk_vbox_new (FALSE, 0);
	_tmp5_ = g_object_ref_sink (_tmp4_);
	_g_object_unref0 (self->priv->left);
	self->priv->left = _tmp5_;
	_tmp6_ = (GtkToolbar*) gtk_toolbar_new ();
	_tmp7_ = g_object_ref_sink (_tmp6_);
	_g_object_unref0 (self->priv->toolbar);
	self->priv->toolbar = _tmp7_;
	_tmp8_ = (GtkToolButton*) gtk_tool_button_new_from_stock (GTK_STOCK_REFRESH);
	_tmp9_ = g_object_ref_sink (_tmp8_);
	_g_object_unref0 (self->priv->refresh);
	self->priv->refresh = _tmp9_;
	_tmp10_ = (GtkToolButton*) gtk_tool_button_new_from_stock (GTK_STOCK_MEDIA_PLAY);
	_tmp11_ = g_object_ref_sink (_tmp10_);
	_g_object_unref0 (self->priv->transferPlayback);
	self->priv->transferPlayback = _tmp11_;
	_tmp12_ = (GtkLabel*) gtk_label_new ("");
	_tmp13_ = g_object_ref_sink (_tmp12_);
	_g_object_unref0 (self->priv->toolInfo);
	self->priv->toolInfo = _tmp13_;
	_tmp14_ = (GtkToolButton*) gtk_tool_button_new_from_stock (GTK_STOCK_SAVE);
	_tmp15_ = g_object_ref_sink (_tmp14_);
	_g_object_unref0 (self->priv->save);
	self->priv->save = _tmp15_;
	_tmp16_ = beat_box_music_tree_view_new (lm, lw, -1);
	_tmp17_ = g_object_ref_sink (_tmp16_);
	_g_object_unref0 (self->priv->similars);
	self->priv->similars = _tmp17_;
	_tmp18_ = beat_box_similar_songs_view_new (self->priv->_lm, self->priv->_lw);
	_tmp19_ = g_object_ref_sink (_tmp18_);
	_g_object_unref0 (self->priv->ssv);
	self->priv->ssv = _tmp19_;
	beat_box_music_tree_view_set_hint (self->priv->similars, "similar");
	_tmp20_ = gtk_tool_item_new ();
	toolInfoBin = g_object_ref_sink (_tmp20_);
	gtk_container_add ((GtkContainer*) toolInfoBin, (GtkWidget*) self->priv->toolInfo);
	gtk_tool_item_set_expand (toolInfoBin, TRUE);
	gtk_tool_item_set_tooltip_text ((GtkToolItem*) self->priv->refresh, "Refresh to show the most current song's similar songs");
	gtk_tool_item_set_tooltip_text ((GtkToolItem*) self->priv->transferPlayback, "Transfer playback to continue playing these songs");
	gtk_tool_item_set_tooltip_text ((GtkToolItem*) self->priv->save, "Save as a playlist");
	gtk_toolbar_insert (self->priv->toolbar, (GtkToolItem*) self->priv->refresh, 0);
	gtk_toolbar_insert (self->priv->toolbar, (GtkToolItem*) self->priv->transferPlayback, 1);
	gtk_toolbar_insert (self->priv->toolbar, toolInfoBin, 2);
	gtk_toolbar_insert (self->priv->toolbar, (GtkToolItem*) self->priv->save, 3);
	gtk_box_pack_start ((GtkBox*) self->priv->left, (GtkWidget*) self->priv->similars, TRUE, TRUE, (guint) 0);
	gtk_box_pack_end ((GtkBox*) self->priv->left, (GtkWidget*) self->priv->toolbar, FALSE, FALSE, (guint) 0);
	gtk_paned_add1 ((GtkPaned*) self, (GtkWidget*) self->priv->left);
	gtk_paned_add2 ((GtkPaned*) self, (GtkWidget*) self->priv->ssv);
	((GtkPaned*) self)->child2_resize = (guint) 1;
	_tmp21_ = beat_box_settings_getMoreWidth (self->priv->_lm->settings);
	gtk_paned_set_position ((GtkPaned*) self, _tmp21_);
	gtk_widget_show_all ((GtkWidget*) self);
	g_signal_connect_object (self->priv->refresh, "clicked", (GCallback) _beat_box_similar_pane_refreshClicked_gtk_tool_button_clicked, self, 0);
	g_signal_connect_object (self->priv->transferPlayback, "clicked", (GCallback) _beat_box_similar_pane_transferPlaybackClicked_gtk_tool_button_clicked, self, 0);
	g_signal_connect_object (self->priv->save, "clicked", (GCallback) _beat_box_similar_pane_saveClicked_gtk_tool_button_clicked, self, 0);
	g_signal_connect_object (((GtkPaned*) self)->child2, "size-allocate", (GCallback) _beat_box_similar_pane_paneHandleSet_gtk_widget_size_allocate, self, 0);
	gtk_widget_hide ((GtkWidget*) self->priv->transferPlayback);
	_g_object_unref0 (toolInfoBin);
	return self;
}


BeatBoxSimilarPane* beat_box_similar_pane_new (BeatBoxLibraryManager* lm, BeatBoxLibraryWindow* lw) {
	return beat_box_similar_pane_construct (BEAT_BOX_TYPE_SIMILAR_PANE, lm, lw);
}


void beat_box_similar_pane_updateSongs (BeatBoxSimilarPane* self, BeatBoxSong* la, GeeCollection* have, GeeCollection* shouldHave) {
	BeatBoxSong* _tmp0_;
	BeatBoxSong* _tmp1_;
	GeeCollection* _tmp2_;
	GeeCollection* _tmp3_;
	GeeCollection* _tmp4_;
	GeeCollection* _tmp5_;
	gboolean _tmp6_ = FALSE;
	GeeCollection* _tmp7_ = NULL;
	GeeCollection* _tmp8_;
	gint _tmp9_;
	GeeSet* _tmp10_ = NULL;
	GeeSet* _tmp11_;
	gint _tmp12_;
	gboolean _tmp13_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (la != NULL);
	g_return_if_fail (have != NULL);
	g_return_if_fail (shouldHave != NULL);
	_tmp0_ = _g_object_ref0 (la);
	_tmp1_ = _tmp0_;
	_g_object_unref0 (self->priv->_next);
	self->priv->_next = _tmp1_;
	_tmp2_ = _g_object_ref0 (have);
	_tmp3_ = _tmp2_;
	_g_object_unref0 (self->_have);
	self->_have = _tmp3_;
	_tmp4_ = _g_object_ref0 (shouldHave);
	_tmp5_ = _tmp4_;
	_g_object_unref0 (self->priv->_shouldHave);
	self->priv->_shouldHave = _tmp5_;
	_tmp7_ = beat_box_library_manager_current_songs (self->priv->_lm);
	_tmp8_ = _tmp7_;
	_tmp9_ = gee_collection_get_size (_tmp8_);
	_tmp10_ = beat_box_music_tree_view_get_songs (self->priv->similars);
	_tmp11_ = _tmp10_;
	_tmp12_ = gee_collection_get_size ((GeeCollection*) _tmp11_);
	if ((_tmp13_ = _tmp9_ == _tmp12_, _g_object_unref0 (_tmp11_), _g_object_unref0 (_tmp8_), _tmp13_)) {
		GeeCollection* _tmp14_ = NULL;
		GeeCollection* _tmp15_;
		GeeSet* _tmp16_ = NULL;
		GeeSet* _tmp17_;
		gboolean _tmp18_;
		_tmp14_ = beat_box_library_manager_current_songs (self->priv->_lm);
		_tmp15_ = _tmp14_;
		_tmp16_ = beat_box_music_tree_view_get_songs (self->priv->similars);
		_tmp17_ = _tmp16_;
		_tmp18_ = gee_collection_contains_all (_tmp15_, (GeeCollection*) _tmp17_);
		_tmp6_ = _tmp18_;
		_g_object_unref0 (_tmp17_);
		_g_object_unref0 (_tmp15_);
	} else {
		_tmp6_ = FALSE;
	}
	if (!_tmp6_) {
		beat_box_similar_pane_updateDisplay (self);
	} else {
		const gchar* _tmp19_ = NULL;
		gchar* _tmp20_;
		gchar* _tmp21_;
		const gchar* _tmp22_ = NULL;
		gchar* _tmp23_;
		gtk_widget_show ((GtkWidget*) self->priv->refresh);
		_tmp19_ = beat_box_song_get_title (self->priv->_next);
		_tmp20_ = g_strconcat ("Refresh to show songs similar to: ", _tmp19_, NULL);
		_tmp21_ = g_strconcat (_tmp20_, " by ", NULL);
		_tmp22_ = beat_box_song_get_artist (self->priv->_next);
		_tmp23_ = g_strconcat (_tmp21_, _tmp22_, NULL);
		gtk_tool_item_set_tooltip_text ((GtkToolItem*) self->priv->refresh, _tmp23_);
		_g_free0 (_tmp23_);
		_g_free0 (_tmp21_);
		_g_free0 (_tmp20_);
		gtk_widget_hide ((GtkWidget*) self->priv->transferPlayback);
	}
}


void beat_box_similar_pane_updateDisplay (BeatBoxSimilarPane* self) {
	gboolean do_transfer;
	gboolean _tmp0_ = FALSE;
	GeeCollection* _tmp1_ = NULL;
	GeeCollection* _tmp2_;
	gint _tmp3_;
	GeeSet* _tmp4_ = NULL;
	GeeSet* _tmp5_;
	gint _tmp6_;
	gboolean _tmp7_;
	BeatBoxSong* _tmp13_;
	BeatBoxSong* _tmp14_;
	const gchar* _tmp15_ = NULL;
	gchar* _tmp16_;
	gchar* _tmp17_;
	const gchar* _tmp18_ = NULL;
	gchar* _tmp19_;
	gchar* _tmp20_;
	g_return_if_fail (self != NULL);
	do_transfer = FALSE;
	_tmp1_ = beat_box_library_manager_current_songs (self->priv->_lm);
	_tmp2_ = _tmp1_;
	_tmp3_ = gee_collection_get_size (_tmp2_);
	_tmp4_ = beat_box_music_tree_view_get_songs (self->priv->similars);
	_tmp5_ = _tmp4_;
	_tmp6_ = gee_collection_get_size ((GeeCollection*) _tmp5_);
	if ((_tmp7_ = _tmp3_ == _tmp6_, _g_object_unref0 (_tmp5_), _g_object_unref0 (_tmp2_), _tmp7_)) {
		GeeCollection* _tmp8_ = NULL;
		GeeCollection* _tmp9_;
		GeeSet* _tmp10_ = NULL;
		GeeSet* _tmp11_;
		gboolean _tmp12_;
		_tmp8_ = beat_box_library_manager_current_songs (self->priv->_lm);
		_tmp9_ = _tmp8_;
		_tmp10_ = beat_box_music_tree_view_get_songs (self->priv->similars);
		_tmp11_ = _tmp10_;
		_tmp12_ = gee_collection_contains_all (_tmp9_, (GeeCollection*) _tmp11_);
		_tmp0_ = _tmp12_;
		_g_object_unref0 (_tmp11_);
		_g_object_unref0 (_tmp9_);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		do_transfer = TRUE;
	}
	beat_box_music_tree_view_populateView (self->priv->similars, self->_have, FALSE);
	beat_box_similar_songs_view_populateView (self->priv->ssv, self->priv->_shouldHave);
	_tmp13_ = _g_object_ref0 (self->priv->_next);
	_tmp14_ = _tmp13_;
	_g_object_unref0 (self->_base);
	self->_base = _tmp14_;
	_tmp15_ = beat_box_song_get_title (self->_base);
	_tmp16_ = g_strconcat ("Songs similar to <b>", _tmp15_, NULL);
	_tmp17_ = g_strconcat (_tmp16_, "</b> by <b>", NULL);
	_tmp18_ = beat_box_song_get_artist (self->_base);
	_tmp19_ = g_strconcat (_tmp17_, _tmp18_, NULL);
	_tmp20_ = g_strconcat (_tmp19_, "</b>", NULL);
	gtk_label_set_markup (self->priv->toolInfo, _tmp20_);
	_g_free0 (_tmp20_);
	_g_free0 (_tmp19_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp16_);
	gtk_widget_hide ((GtkWidget*) self->priv->refresh);
	gtk_widget_show ((GtkWidget*) self->priv->transferPlayback);
	gtk_widget_show ((GtkWidget*) self->priv->save);
	if (do_transfer) {
		beat_box_similar_pane_transferPlaybackClicked (self);
	}
	if (self->priv->_lm->song_info->song != NULL) {
		gint _tmp21_;
		_tmp21_ = beat_box_song_get_rowid (self->priv->_lm->song_info->song);
		beat_box_music_tree_view_updateSong (self->priv->similars, _tmp21_);
	}
}


static void beat_box_similar_pane_real_refreshClicked (BeatBoxSimilarPane* self) {
	g_return_if_fail (self != NULL);
	beat_box_similar_pane_updateDisplay (self);
}


void beat_box_similar_pane_refreshClicked (BeatBoxSimilarPane* self) {
	BEAT_BOX_SIMILAR_PANE_GET_CLASS (self)->refreshClicked (self);
}


static void beat_box_similar_pane_real_transferPlaybackClicked (BeatBoxSimilarPane* self) {
	g_return_if_fail (self != NULL);
	beat_box_music_tree_view_setAsCurrentList (self->priv->similars, "0");
	gtk_widget_hide ((GtkWidget*) self->priv->transferPlayback);
}


void beat_box_similar_pane_transferPlaybackClicked (BeatBoxSimilarPane* self) {
	BEAT_BOX_SIMILAR_PANE_GET_CLASS (self)->transferPlaybackClicked (self);
}


static void beat_box_similar_pane_real_saveClicked (BeatBoxSimilarPane* self) {
	BeatBoxPlaylist* _tmp0_ = NULL;
	BeatBoxPlaylist* p;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = beat_box_playlist_new ();
	p = _tmp0_;
	_tmp1_ = beat_box_song_get_title (self->_base);
	_tmp2_ = g_strconcat ("Similar to ", _tmp1_, NULL);
	beat_box_playlist_set_name (p, _tmp2_);
	_g_free0 (_tmp2_);
	{
		GeeSet* _tmp3_ = NULL;
		GeeSet* _tmp4_;
		GeeIterator* _tmp5_ = NULL;
		GeeIterator* _tmp6_;
		GeeIterator* _id_it;
		_tmp3_ = beat_box_music_tree_view_get_songs (self->priv->similars);
		_tmp4_ = _tmp3_;
		_tmp5_ = gee_iterable_iterator ((GeeIterable*) _tmp4_);
		_id_it = (_tmp6_ = _tmp5_, _g_object_unref0 (_tmp4_), _tmp6_);
		while (TRUE) {
			gboolean _tmp7_;
			gpointer _tmp8_ = NULL;
			gint id;
			BeatBoxSong* _tmp9_ = NULL;
			BeatBoxSong* _tmp10_;
			_tmp7_ = gee_iterator_next (_id_it);
			if (!_tmp7_) {
				break;
			}
			_tmp8_ = gee_iterator_get (_id_it);
			id = GPOINTER_TO_INT (_tmp8_);
			_tmp9_ = beat_box_library_manager_song_from_id (self->priv->_lm, id);
			_tmp10_ = _tmp9_;
			beat_box_playlist_addSong (p, _tmp10_);
			_g_object_unref0 (_tmp10_);
		}
		_g_object_unref0 (_id_it);
	}
	beat_box_library_manager_add_playlist (self->priv->_lm, p);
	beat_box_library_window_addSideListItem (self->priv->_lw, (GObject*) p);
	gtk_widget_hide ((GtkWidget*) self->priv->save);
	_g_object_unref0 (p);
}


void beat_box_similar_pane_saveClicked (BeatBoxSimilarPane* self) {
	BEAT_BOX_SIMILAR_PANE_GET_CLASS (self)->saveClicked (self);
}


static void beat_box_similar_pane_real_paneHandleSet (BeatBoxSimilarPane* self, GdkRectangle* rectangle) {
	gint _tmp0_;
	gint _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = beat_box_settings_getMoreWidth (self->priv->_lm->settings);
	_tmp1_ = gtk_paned_get_position ((GtkPaned*) self);
	if (_tmp0_ != _tmp1_) {
		gint _tmp2_;
		_tmp2_ = gtk_paned_get_position ((GtkPaned*) self);
		beat_box_settings_setMoreWidth (self->priv->_lm->settings, _tmp2_);
	}
}


void beat_box_similar_pane_paneHandleSet (BeatBoxSimilarPane* self, GdkRectangle* rectangle) {
	BEAT_BOX_SIMILAR_PANE_GET_CLASS (self)->paneHandleSet (self, rectangle);
}


static void beat_box_similar_pane_class_init (BeatBoxSimilarPaneClass * klass) {
	beat_box_similar_pane_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (BeatBoxSimilarPanePrivate));
	BEAT_BOX_SIMILAR_PANE_CLASS (klass)->refreshClicked = beat_box_similar_pane_real_refreshClicked;
	BEAT_BOX_SIMILAR_PANE_CLASS (klass)->transferPlaybackClicked = beat_box_similar_pane_real_transferPlaybackClicked;
	BEAT_BOX_SIMILAR_PANE_CLASS (klass)->saveClicked = beat_box_similar_pane_real_saveClicked;
	BEAT_BOX_SIMILAR_PANE_CLASS (klass)->paneHandleSet = beat_box_similar_pane_real_paneHandleSet;
	G_OBJECT_CLASS (klass)->finalize = beat_box_similar_pane_finalize;
	g_signal_new ("playlist_saved", BEAT_BOX_TYPE_SIMILAR_PANE, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, BEAT_BOX_TYPE_PLAYLIST);
}


static void beat_box_similar_pane_instance_init (BeatBoxSimilarPane * self) {
	self->priv = BEAT_BOX_SIMILAR_PANE_GET_PRIVATE (self);
}


static void beat_box_similar_pane_finalize (GObject* obj) {
	BeatBoxSimilarPane * self;
	self = BEAT_BOX_SIMILAR_PANE (obj);
	_g_object_unref0 (self->priv->_lm);
	_g_object_unref0 (self->priv->_lw);
	_g_object_unref0 (self->_base);
	_g_object_unref0 (self->priv->_next);
	_g_object_unref0 (self->_have);
	_g_object_unref0 (self->priv->_shouldHave);
	_g_object_unref0 (self->priv->left);
	_g_object_unref0 (self->priv->toolbar);
	_g_object_unref0 (self->priv->refresh);
	_g_object_unref0 (self->priv->toolInfo);
	_g_object_unref0 (self->priv->transferPlayback);
	_g_object_unref0 (self->priv->save);
	_g_object_unref0 (self->priv->similars);
	_g_object_unref0 (self->priv->ssv);
	G_OBJECT_CLASS (beat_box_similar_pane_parent_class)->finalize (obj);
}


GType beat_box_similar_pane_get_type (void) {
	static volatile gsize beat_box_similar_pane_type_id__volatile = 0;
	if (g_once_init_enter (&beat_box_similar_pane_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BeatBoxSimilarPaneClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) beat_box_similar_pane_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BeatBoxSimilarPane), 0, (GInstanceInitFunc) beat_box_similar_pane_instance_init, NULL };
		GType beat_box_similar_pane_type_id;
		beat_box_similar_pane_type_id = g_type_register_static (GTK_TYPE_HPANED, "BeatBoxSimilarPane", &g_define_type_info, 0);
		g_once_init_leave (&beat_box_similar_pane_type_id__volatile, beat_box_similar_pane_type_id);
	}
	return beat_box_similar_pane_type_id__volatile;
}



